{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "\n",
    "from pytorch_pretrained_bert import BertTokenizer, BertModel, BertForMaskedLM\n",
    "\n",
    "# Load pre-trained model tokenizer (vocabulary)\n",
    "tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')\n",
    "\n",
    "# Tokenized input\n",
    "text1 = \"This is Saeedeh. I am a student at the university of Alberta.\"\n",
    "text2 = \"I am Saeedeh.\"\n",
    "tokenized_text1 = tokenizer.tokenize(text1)\n",
    "tokenized_text2 = tokenizer.tokenize(text2)\n",
    "print(tokenized_text1)\n",
    "print(tokenized_text2)\n",
    "\n",
    "['this', 'is', 'sa', '##eed', '##eh', '.', 'i', 'am', 'a', 'student', 'at', 'the', 'university', 'of', 'alberta', '.']\n",
    "['i', 'am', 'sa', '##eed', '##eh', '.']\n",
    "\n",
    "from bert_serving.client import BertClient\n",
    "from sklearn.metrics.pairwise import cosine_similarity\n",
    "\n",
    "# Uncomment the following line if the BERT server that is running locally (on the same physical server that the client will be running on).\n",
    "print('before client')\n",
    "client = BertClient()\n",
    "\n",
    "# Uncomment the following line if the BERT server is running remotely (on a different physical server than the client will be running on).\n",
    "# You must specify the IP of the remote server and the ports\n",
    "\n",
    "#client = BertClient(ip='129.128.208.15')\n",
    "print('after client')\n",
    "\n",
    "before client\n",
    "\n",
    "from bert_serving.client import BertClient\n",
    "\n",
    "ls\n",
    "\n",
    "bert_config.json                     bert_model.ckpt.index  vocab.txt\n",
    "bert_model.ckpt.data-00000-of-00001  bert_model.ckpt.meta\n",
    "\n",
    "pwd\n",
    "\n",
    "/home/ubuntu/anaconda3/lib/python3.7/site-packages\n",
    "\n",
    "'/home/ubuntu/virt-env/jupyterNB'\n",
    "\n",
    " \n",
    "\n",
    "pip install https://storage.googleapis.com/cloud-tpu-checkpoints/albert/checkpoints/albert_v2_base.tar.gz\n",
    "\n",
    "Collecting https://storage.googleapis.com/cloud-tpu-checkpoints/albert/checkpoints/albert_v2_base.tar.gz\n",
    "  Using cached https://storage.googleapis.com/cloud-tpu-checkpoints/albert/checkpoints/albert_v2_base.tar.gz (44.0 MB)\n",
    "    ERROR: Command errored out with exit status 1:\n",
    "     command: /home/ubuntu/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-req-build-1vhf0yv8/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-req-build-1vhf0yv8/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-s9ct478j\n",
    "         cwd: /tmp/pip-req-build-1vhf0yv8/\n",
    "    Complete output (5 lines):\n",
    "    Traceback (most recent call last):\n",
    "      File \"<string>\", line 1, in <module>\n",
    "      File \"/home/ubuntu/anaconda3/lib/python3.7/tokenize.py\", line 447, in open\n",
    "        buffer = _builtin_open(filename, 'rb')\n",
    "    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-1vhf0yv8/setup.py'\n",
    "    ----------------------------------------\n",
    "ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
    "Note: you may need to restart the kernel to use updated packages.\n",
    "\n",
    "pip install tf-nightly-gpu\n",
    "\n",
    "Collecting tf-nightly-gpu\n",
    "  Downloading tf_nightly_gpu-2.4.0.dev20200707-cp37-cp37m-manylinux2010_x86_64.whl (322.7 MB)\n",
    "     |████████████████████████████████| 322.7 MB 2.9 kB/s  eta 0:00:01     |██████████▉                     | 108.8 MB 19.9 MB/s eta 0:00:11     |█████████████████████████████▎  | 294.9 MB 53.2 MB/s eta 0:00:01\n",
    "Requirement already satisfied: tf-estimator-nightly in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tf-nightly-gpu) (2.4.0.dev2020070601)\n",
    "Requirement already satisfied: six>=1.12.0 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tf-nightly-gpu) (1.12.0)\n",
    "Requirement already satisfied: astunparse==1.6.3 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tf-nightly-gpu) (1.6.3)\n",
    "Requirement already satisfied: opt-einsum>=2.3.2 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tf-nightly-gpu) (3.2.1)\n",
    "Requirement already satisfied: tb-nightly<2.4.0a0,>=2.3.0a0 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tf-nightly-gpu) (2.3.0a20200706)\n",
    "Requirement already satisfied: gast==0.3.3 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tf-nightly-gpu) (0.3.3)\n",
    "Requirement already satisfied: h5py<2.11.0,>=2.10.0 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tf-nightly-gpu) (2.10.0)\n",
    "Requirement already satisfied: keras-preprocessing<1.2,>=1.1.1 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tf-nightly-gpu) (1.1.2)\n",
    "Requirement already satisfied: wrapt>=1.11.1 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tf-nightly-gpu) (1.11.2)\n",
    "Requirement already satisfied: grpcio>=1.8.6 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tf-nightly-gpu) (1.30.0)\n",
    "Requirement already satisfied: termcolor>=1.1.0 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tf-nightly-gpu) (1.1.0)\n",
    "Requirement already satisfied: protobuf>=3.9.2 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tf-nightly-gpu) (3.12.2)\n",
    "Requirement already satisfied: numpy<1.19.0,>=1.16.0 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tf-nightly-gpu) (1.17.2)\n",
    "Requirement already satisfied: wheel>=0.26 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tf-nightly-gpu) (0.33.6)\n",
    "Requirement already satisfied: absl-py>=0.7.0 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tf-nightly-gpu) (0.9.0)\n",
    "Requirement already satisfied: google-pasta>=0.1.8 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tf-nightly-gpu) (0.2.0)\n",
    "Requirement already satisfied: scipy==1.4.1 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tf-nightly-gpu) (1.4.1)\n",
    "Requirement already satisfied: markdown>=2.6.8 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tb-nightly<2.4.0a0,>=2.3.0a0->tf-nightly-gpu) (3.2.2)\n",
    "Requirement already satisfied: google-auth<2,>=1.6.3 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tb-nightly<2.4.0a0,>=2.3.0a0->tf-nightly-gpu) (1.18.0)\n",
    "Requirement already satisfied: werkzeug>=0.11.15 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tb-nightly<2.4.0a0,>=2.3.0a0->tf-nightly-gpu) (0.16.0)\n",
    "Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tb-nightly<2.4.0a0,>=2.3.0a0->tf-nightly-gpu) (0.4.1)\n",
    "Requirement already satisfied: setuptools>=41.0.0 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tb-nightly<2.4.0a0,>=2.3.0a0->tf-nightly-gpu) (49.1.0)\n",
    "Requirement already satisfied: requests<3,>=2.21.0 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tb-nightly<2.4.0a0,>=2.3.0a0->tf-nightly-gpu) (2.22.0)\n",
    "Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tb-nightly<2.4.0a0,>=2.3.0a0->tf-nightly-gpu) (1.6.0.post3)\n",
    "Requirement already satisfied: importlib-metadata; python_version < \"3.8\" in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from markdown>=2.6.8->tb-nightly<2.4.0a0,>=2.3.0a0->tf-nightly-gpu) (0.23)\n",
    "Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from google-auth<2,>=1.6.3->tb-nightly<2.4.0a0,>=2.3.0a0->tf-nightly-gpu) (4.1.0)\n",
    "Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from google-auth<2,>=1.6.3->tb-nightly<2.4.0a0,>=2.3.0a0->tf-nightly-gpu) (0.2.8)\n",
    "Requirement already satisfied: rsa<5,>=3.1.4; python_version >= \"3\" in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from google-auth<2,>=1.6.3->tb-nightly<2.4.0a0,>=2.3.0a0->tf-nightly-gpu) (4.6)\n",
    "Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tb-nightly<2.4.0a0,>=2.3.0a0->tf-nightly-gpu) (1.3.0)\n",
    "Requirement already satisfied: certifi>=2017.4.17 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from requests<3,>=2.21.0->tb-nightly<2.4.0a0,>=2.3.0a0->tf-nightly-gpu) (2019.9.11)\n",
    "Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from requests<3,>=2.21.0->tb-nightly<2.4.0a0,>=2.3.0a0->tf-nightly-gpu) (3.0.4)\n",
    "Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from requests<3,>=2.21.0->tb-nightly<2.4.0a0,>=2.3.0a0->tf-nightly-gpu) (1.24.2)\n",
    "Requirement already satisfied: idna<2.9,>=2.5 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from requests<3,>=2.21.0->tb-nightly<2.4.0a0,>=2.3.0a0->tf-nightly-gpu) (2.8)\n",
    "Requirement already satisfied: zipp>=0.5 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from importlib-metadata; python_version < \"3.8\"->markdown>=2.6.8->tb-nightly<2.4.0a0,>=2.3.0a0->tf-nightly-gpu) (0.6.0)\n",
    "Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tb-nightly<2.4.0a0,>=2.3.0a0->tf-nightly-gpu) (0.4.8)\n",
    "Requirement already satisfied: oauthlib>=3.0.0 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tb-nightly<2.4.0a0,>=2.3.0a0->tf-nightly-gpu) (3.1.0)\n",
    "Requirement already satisfied: more-itertools in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from zipp>=0.5->importlib-metadata; python_version < \"3.8\"->markdown>=2.6.8->tb-nightly<2.4.0a0,>=2.3.0a0->tf-nightly-gpu) (7.2.0)\n",
    "Installing collected packages: tf-nightly-gpu\n",
    "Successfully installed tf-nightly-gpu-2.4.0.dev20200707\n",
    "Note: you may need to restart the kernel to use updated packages.\n",
    "\n",
    "pip install albert-tensorflow\n",
    "\n",
    "Collecting albert-tensorflow\n",
    "  Downloading albert_tensorflow-1.1-py3-none-any.whl (81 kB)\n",
    "     |████████████████████████████████| 81 kB 893 kB/s eta 0:00:011\n",
    "Requirement already satisfied: six in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from albert-tensorflow) (1.12.0)\n",
    "Installing collected packages: albert-tensorflow\n",
    "Successfully installed albert-tensorflow-1.1\n",
    "Note: you may need to restart the kernel to use updated packages.\n",
    "\n",
    "pip install bert-serving-server\n",
    "\n",
    "Requirement already satisfied: bert-serving-server in /home/ubuntu/anaconda3/lib/python3.7/site-packages (1.10.0)\n",
    "Requirement already satisfied: numpy in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from bert-serving-server) (1.17.2)\n",
    "Requirement already satisfied: pyzmq>=17.1.0 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from bert-serving-server) (18.1.0)\n",
    "Requirement already satisfied: six in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from bert-serving-server) (1.12.0)\n",
    "Requirement already satisfied: GPUtil>=1.3.0 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from bert-serving-server) (1.4.0)\n",
    "Requirement already satisfied: termcolor>=1.1 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from bert-serving-server) (1.1.0)\n",
    "Note: you may need to restart the kernel to use updated packages.\n",
    "\n",
    "bert-serving-server -model_dir /uncased_bert_model -num_worker 4\n",
    "\n",
    "  File \"<ipython-input-22-993cf4e01acd>\", line 1\n",
    "    tar -xvzf bert-serving-start.tar.gz\n",
    "                 ^\n",
    "SyntaxError: invalid syntax\n",
    "\n",
    "from bert_serving.client import BertClient\n",
    "client = BertClient()\n",
    "\n",
    "---------------------------------------------------------------------------\n",
    "KeyboardInterrupt                         Traceback (most recent call last)\n",
    "<ipython-input-37-0426c3497f7a> in <module>\n",
    "      1 from bert_serving.client import BertClient\n",
    "----> 2 client = BertClient()\n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/bert_serving/client/__init__.py in __init__(self, ip, port, port_out, output_fmt, show_server_config, identity, check_version, check_length, check_token_info, ignore_all_checks, timeout)\n",
    "    106 \n",
    "    107         if not ignore_all_checks and (check_version or show_server_config or check_length or check_token_info):\n",
    "--> 108             s_status = self.server_config\n",
    "    109 \n",
    "    110             if check_version and s_status['server_version'] != self.status['client_version']:\n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/bert_serving/client/__init__.py in arg_wrapper(self, *args, **kwargs)\n",
    "    204                 self.receiver.setsockopt(zmq.RCVTIMEO, self.timeout)\n",
    "    205             try:\n",
    "--> 206                 return func(self, *args, **kwargs)\n",
    "    207             except zmq.error.Again as _e:\n",
    "    208                 t_e = TimeoutError(\n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/bert_serving/client/__init__.py in server_config(self)\n",
    "    230         \"\"\"\n",
    "    231         req_id = self._send(b'SHOW_CONFIG')\n",
    "--> 232         return jsonapi.loads(self._recv(req_id).content[1])\n",
    "    233 \n",
    "    234     @property\n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/bert_serving/client/__init__.py in _recv(self, wait_for_req_id)\n",
    "    151 \n",
    "    152                 # receive a response\n",
    "--> 153                 response = self.receiver.recv_multipart()\n",
    "    154                 request_id = int(response[-1])\n",
    "    155 \n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/zmq/sugar/socket.py in recv_multipart(self, flags, copy, track)\n",
    "    473             for any of the reasons :func:`~Socket.recv` might fail\n",
    "    474         \"\"\"\n",
    "--> 475         parts = [self.recv(flags, copy=copy, track=track)]\n",
    "    476         # have first part already, only loop while more to receive\n",
    "    477         while self.getsockopt(zmq.RCVMORE):\n",
    "\n",
    "zmq/backend/cython/socket.pyx in zmq.backend.cython.socket.Socket.recv()\n",
    "\n",
    "zmq/backend/cython/socket.pyx in zmq.backend.cython.socket.Socket.recv()\n",
    "\n",
    "zmq/backend/cython/socket.pyx in zmq.backend.cython.socket._recv_copy()\n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/zmq/backend/cython/checkrc.pxd in zmq.backend.cython.checkrc._check_rc()\n",
    "\n",
    "KeyboardInterrupt: \n",
    "\n",
    "from bert_serving.client import BertClient\n",
    "bc = BertClient()\n",
    "print(\"Yaaaaay\")\n",
    "\n",
    "!pip install https://storage.googleapis.com/bert_models/2018_10_18/cased_L-12_H-768_A-12.zip\n",
    "\n",
    "Collecting https://storage.googleapis.com/bert_models/2018_10_18/cased_L-12_H-768_A-12.zip\n",
    "  Cache entry deserialization failed, entry ignored\n",
    "  Downloading https://storage.googleapis.com/bert_models/2018_10_18/cased_L-12_H-768_A-12.zip (404.3MB)\n",
    "    100% |████████████████████████████████| 404.3MB 3.6kB/s  eta 0:00:01  10% |███▌                            | 44.4MB 27.3MB/s eta 0:00:14    15% |█████                           | 64.5MB 22.8MB/s eta 0:00:15    24% |███████▉                        | 99.4MB 27.4MB/s eta 0:00:12    36% |███████████▊                    | 147.7MB 27.3MB/s eta 0:00:10    36% |███████████▉                    | 149.1MB 27.1MB/s eta 0:00:10    38% |████████████▍                   | 157.0MB 24.5MB/s eta 0:00:11    45% |██████████████▌                 | 183.7MB 23.9MB/s eta 0:00:10    47% |███████████████                 | 190.2MB 23.5MB/s eta 0:00:10    47% |███████████████▏                | 191.7MB 37.4MB/s eta 0:00:06    49% |████████████████                | 201.1MB 27.0MB/s eta 0:00:08    50% |████████████████▏               | 203.8MB 25.3MB/s eta 0:00:08    52% |████████████████▉               | 212.7MB 16.6MB/s eta 0:00:12��█████████████████▋           | 260.2MB 48.1MB/s eta 0:00:03/s eta 0:00:03    74% |████████████████████████        | 302.3MB 51.0MB/s eta 0:00:03\n",
    "    Complete output from command python setup.py egg_info:\n",
    "    Traceback (most recent call last):\n",
    "      File \"<string>\", line 1, in <module>\n",
    "      File \"/usr/lib/python3.6/tokenize.py\", line 452, in open\n",
    "        buffer = _builtin_open(filename, 'rb')\n",
    "    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-38q0f_1c-build/setup.py'\n",
    "    \n",
    "    ----------------------------------------\n",
    "Command \"python setup.py egg_info\" failed with error code 1 in /tmp/pip-38q0f_1c-build/\n",
    "\n",
    "ls\n",
    "\n",
    "classifier_utils.py  optimization.py               run_pretraining.py\n",
    "__init__.py          optimization_test.py          run_squad.py\n",
    "lamb_optimizer.py    __pycache__/                  squad_utils.py\n",
    "modeling.py          run_classifier.py             tokenization.py\n",
    "modeling_test.py     run_classifier_with_tfhub.py  tokenization_test.py\n",
    "\n",
    "pwd\n",
    "\n",
    "'/home/ubuntu/anaconda3/lib/python3.7/site-packages'\n",
    "\n",
    "!bert-serving-start -model_dir uncased_L-24_H-1024_A-16\n",
    "\n",
    "/home/ubuntu/anaconda3/lib/python3.7/site-packages/bert_serving/server/helper.py:176: UserWarning: Tensorflow 2.2.0 is not tested! It may or may not work. Feel free to submit an issue at https://github.com/hanxiao/bert-as-service/issues/\n",
    "  'Feel free to submit an issue at https://github.com/hanxiao/bert-as-service/issues/' % tf.__version__)\n",
    "usage: /home/ubuntu/anaconda3/bin/bert-serving-start -model_dir uncased_L-24_H-1024_A-16\n",
    "                 ARG   VALUE\n",
    "__________________________________________________\n",
    "           ckpt_name = bert_model.ckpt\n",
    "         config_name = bert_config.json\n",
    "                cors = *\n",
    "                 cpu = False\n",
    "          device_map = []\n",
    "       do_lower_case = True\n",
    "  fixed_embed_length = False\n",
    "                fp16 = False\n",
    " gpu_memory_fraction = 0.5\n",
    "       graph_tmp_dir = None\n",
    "    http_max_connect = 10\n",
    "           http_port = None\n",
    "        mask_cls_sep = False\n",
    "      max_batch_size = 256\n",
    "         max_seq_len = 25\n",
    "           model_dir = uncased_L-24_H-1024_A-16\n",
    "no_position_embeddings = False\n",
    "    no_special_token = False\n",
    "          num_worker = 1\n",
    "       pooling_layer = [-2]\n",
    "    pooling_strategy = REDUCE_MEAN\n",
    "                port = 5555\n",
    "            port_out = 5556\n",
    "       prefetch_size = 10\n",
    " priority_batch_size = 16\n",
    "show_tokens_to_client = False\n",
    "     tuned_model_dir = None\n",
    "             verbose = False\n",
    "                 xla = False\n",
    "\n",
    "I:VENTILATOR:[__i:__i: 67]:freeze, optimize and export graph, could take a while...\n",
    "I:GRAPHOPT:[gra:opt: 53]:model config: uncased_L-24_H-1024_A-16/bert_config.json\n",
    "I:GRAPHOPT:[gra:opt: 56]:checkpoint: uncased_L-24_H-1024_A-16/bert_model.ckpt\n",
    "I:GRAPHOPT:[gra:opt: 60]:build graph...\n",
    "E:GRAPHOPT:[gra:opt:154]:fail to optimize the graph!\n",
    "Traceback (most recent call last):\n",
    "  File \"/home/ubuntu/anaconda3/lib/python3.7/site-packages/bert_serving/server/graph.py\", line 62, in optimize_graph\n",
    "    input_ids = tf.placeholder(tf.int32, (None, None), 'input_ids')\n",
    "AttributeError: module 'tensorflow' has no attribute 'placeholder'\n",
    "Traceback (most recent call last):\n",
    "  File \"/home/ubuntu/anaconda3/bin/bert-serving-start\", line 10, in <module>\n",
    "    sys.exit(main())\n",
    "  File \"/home/ubuntu/anaconda3/lib/python3.7/site-packages/bert_serving/server/cli/__init__.py\", line 4, in main\n",
    "    with BertServer(get_run_args()) as server:\n",
    "  File \"/home/ubuntu/anaconda3/lib/python3.7/site-packages/bert_serving/server/__init__.py\", line 71, in __init__\n",
    "    self.graph_path, self.bert_config = pool.apply(optimize_graph, (self.args,))\n",
    "TypeError: cannot unpack non-iterable NoneType object\n",
    "\n",
    "!pip install Keras==2.3.1\n",
    "\n",
    "Collecting Keras==2.3.1\n",
    "  Downloading Keras-2.3.1-py2.py3-none-any.whl (377 kB)\n",
    "     |████████████████████████████████| 377 kB 1.8 MB/s eta 0:00:01\n",
    "Requirement already satisfied: numpy>=1.9.1 in /home/ubuntu/virt-env/lib/python3.6/site-packages (from Keras==2.3.1) (1.19.0)\n",
    "Requirement already satisfied: keras-applications>=1.0.6 in /home/ubuntu/virt-env/lib/python3.6/site-packages (from Keras==2.3.1) (1.0.8)\n",
    "Requirement already satisfied: h5py in /home/ubuntu/virt-env/lib/python3.6/site-packages (from Keras==2.3.1) (2.10.0)\n",
    "Collecting pyyaml\n",
    "  Downloading PyYAML-5.3.1.tar.gz (269 kB)\n",
    "     |████████████████████████████████| 269 kB 5.5 MB/s eta 0:00:01\n",
    "Requirement already satisfied: scipy>=0.14 in /home/ubuntu/virt-env/lib/python3.6/site-packages (from Keras==2.3.1) (1.4.1)\n",
    "Requirement already satisfied: keras-preprocessing>=1.0.5 in /home/ubuntu/virt-env/lib/python3.6/site-packages (from Keras==2.3.1) (1.1.2)\n",
    "Requirement already satisfied: six>=1.9.0 in /home/ubuntu/virt-env/lib/python3.6/site-packages (from Keras==2.3.1) (1.15.0)\n",
    "Building wheels for collected packages: pyyaml\n",
    "  Building wheel for pyyaml (setup.py) ... done\n",
    "  Created wheel for pyyaml: filename=PyYAML-5.3.1-cp36-cp36m-linux_x86_64.whl size=44621 sha256=175b8c4bf37d85c83379df175582179f7d26416574b2d140a631f673fcd7b80a\n",
    "  Stored in directory: /home/ubuntu/.cache/pip/wheels/e5/9d/ad/2ee53cf262cba1ffd8afe1487eef788ea3f260b7e6232a80fc\n",
    "Successfully built pyyaml\n",
    "Installing collected packages: pyyaml, Keras\n",
    "Successfully installed Keras-2.3.1 pyyaml-5.3.1\n",
    "\n",
    "cd anaconda3/lib/python3.7/site-packages\n",
    "\n",
    "/home/ubuntu/anaconda3/lib/python3.7/site-packages\n",
    "\n",
    "print(Keras.__version__)\n",
    "\n",
    "---------------------------------------------------------------------------\n",
    "NameError                                 Traceback (most recent call last)\n",
    "<ipython-input-35-7bcf3b4d5c4a> in <module>\n",
    "----> 1 print(Keras.__version__)\n",
    "\n",
    "NameError: name 'Keras' is not defined\n",
    "\n",
    "import tensorflow as tf\n",
    "print(tf.__version__)\n",
    "\n",
    "2.4.0-dev20200707\n",
    "\n",
    "!wget https://storage.googleapis.com/bert_models/2018_10_18/uncased_L-24_H-1024_A-16.zip -O temp.zip\n",
    "\n",
    "--2020-07-10 22:11:06--  https://storage.googleapis.com/bert_models/2018_10_18/uncased_L-24_H-1024_A-16.zip\n",
    "Resolving storage.googleapis.com (storage.googleapis.com)... 172.217.14.208, 172.217.14.240, 2607:f8b0:400a:801::2010, ...\n",
    "Connecting to storage.googleapis.com (storage.googleapis.com)|172.217.14.208|:443... connected.\n",
    "HTTP request sent, awaiting response... 200 OK\n",
    "Length: 1247797031 (1.2G) [application/zip]\n",
    "Saving to: ‘temp.zip’\n",
    "\n",
    "temp.zip            100%[===================>]   1.16G  69.0MB/s    in 19s     \n",
    "\n",
    "2020-07-10 22:11:25 (63.9 MB/s) - ‘temp.zip’ saved [1247797031/1247797031]\n",
    "\n",
    "!unzip temp.zip\n",
    "\n",
    "Archive:  temp.zip\n",
    "   creating: uncased_L-24_H-1024_A-16/\n",
    "  inflating: uncased_L-24_H-1024_A-16/bert_model.ckpt.meta  \n",
    "  inflating: uncased_L-24_H-1024_A-16/bert_model.ckpt.data-00000-of-00001  \n",
    "  inflating: uncased_L-24_H-1024_A-16/vocab.txt  \n",
    "  inflating: uncased_L-24_H-1024_A-16/bert_model.ckpt.index  \n",
    "  inflating: uncased_L-24_H-1024_A-16/bert_config.json  \n",
    "\n",
    "!rm temp.zip\n",
    "\n",
    "cd anaconda3/lib/python3.7/site-packages\n",
    "\n",
    "/home/ubuntu/anaconda3/lib/python3.7/site-packages\n",
    "\n",
    "cd anaconda3/lib/python3.7/site-packages\n",
    "\n",
    "/home/ubuntu/anaconda3/lib/python3.7/site-packages\n",
    "\n",
    "!sed -i 's/tf.logging/tf.compat.v1.logging/g' bert_serving/server/helper.py\n",
    "\n",
    "!sed -i 's/tf.ConfigProto/tf.compat.v1.ConfigProto/g' bert_serving/server/graph.py\n",
    "\n",
    "!sed -i 's/tf.gfile/tf.io.gfile/g' bert_serving/server/graph.py\n",
    "\n",
    "!chmod a+rwx bert_serving/server/graph.py\n",
    "\n",
    "ls -l bert_serving/server/graph.py\n",
    "\n",
    "ls\n",
    "\n",
    "absl/\n",
    "absl_py-0.9.0.dist-info/\n",
    "alabaster/\n",
    "alabaster-0.7.12.dist-info/\n",
    "albert/\n",
    "albert_tensorflow-1.1.dist-info/\n",
    "anaconda_client-1.7.2-py3.7.egg-info/\n",
    "anaconda_navigator/\n",
    "anaconda_navigator-1.9.7-py3.7.egg-info/\n",
    "anaconda_project/\n",
    "anaconda_project-0.8.3.dist-info/\n",
    "apiclient/\n",
    "asn1crypto/\n",
    "asn1crypto-1.0.1.dist-info/\n",
    "astor/\n",
    "astor-0.8.1.dist-info/\n",
    "astroid/\n",
    "astroid-2.3.1.dist-info/\n",
    "astropy/\n",
    "astropy-3.2.2-py3.7.egg-info/\n",
    "astunparse/\n",
    "astunparse-1.6.3.dist-info/\n",
    "atomicwrites/\n",
    "atomicwrites-1.3.0-py3.7.egg-info/\n",
    "attr/\n",
    "attrs-19.2.0.dist-info/\n",
    "babel/\n",
    "Babel-2.7.0.dist-info/\n",
    "backcall/\n",
    "backcall-0.1.0.dist-info/\n",
    "backports/\n",
    "backports.functools_lru_cache-1.5-py2.7.egg-info/\n",
    "backports.os-0.1.1-py3.7.egg-info/\n",
    "backports.shutil_get_terminal_size-1.0.0.dist-info/\n",
    "backports.tempfile-1.0.dist-info/\n",
    "backports.weakref-1.0.post1-py2.7.egg-info/\n",
    "beautifulsoup4-4.8.0.dist-info/\n",
    "bert/\n",
    "bert-2.2.0.dist-info/\n",
    "bert_serving/\n",
    "bert_serving_client-1.10.0.dist-info/\n",
    "bert_serving_server-1.10.0.dist-info/\n",
    "bert_tensorflow-1.0.1.dist-info/\n",
    "binstar_client/\n",
    "bitarray/\n",
    "bitarray-1.0.1.dist-info/\n",
    "bkcharts/\n",
    "bkcharts-0.2-py3.7.egg-info/\n",
    "bleach/\n",
    "bleach-3.1.0-py3.7.egg-info/\n",
    "bokeh/\n",
    "bokeh-1.3.4.dist-info/\n",
    "boto/\n",
    "boto-2.49.0-py3.7.egg-info\n",
    "boto3/\n",
    "boto3-1.14.17.dist-info/\n",
    "botocore/\n",
    "botocore-1.17.17.dist-info/\n",
    "bottleneck/\n",
    "Bottleneck-1.2.1-py3.7.egg-info/\n",
    "bs4/\n",
    "cachetools/\n",
    "cachetools-4.1.1.dist-info/\n",
    "caffe2/\n",
    "certifi/\n",
    "certifi-2020.6.20.dist-info/\n",
    "cffi/\n",
    "cffi-1.12.3.dist-info/\n",
    "_cffi_backend.cpython-37m-x86_64-linux-gnu.so*\n",
    "chardet/\n",
    "chardet-3.0.4.dist-info/\n",
    "click/\n",
    "Click-7.0-py3.7.egg-info/\n",
    "cloudpickle/\n",
    "cloudpickle-1.2.2.dist-info/\n",
    "clyent/\n",
    "clyent-1.2.2-py3.7.egg-info/\n",
    "colorama/\n",
    "colorama-0.4.1-py3.7.egg-info/\n",
    "conda/\n",
    "conda-4.8.3-py3.7.egg-info/\n",
    "conda_build/\n",
    "conda_build-3.18.9-py3.7.egg-info/\n",
    "conda_env/\n",
    "conda_package_handling/\n",
    "conda_package_handling-1.6.0.dist-info/\n",
    "conda_verify/\n",
    "conda_verify-3.4.2.dist-info/\n",
    "contextlib2-0.6.0.dist-info/\n",
    "contextlib2.py\n",
    "cpuinfo/\n",
    "Crypto/\n",
    "cryptography/\n",
    "cryptography-2.7.dist-info/\n",
    "curl/\n",
    "cv2/\n",
    "cycler-0.10.0-py3.7.egg-info/\n",
    "cycler.py\n",
    "Cython/\n",
    "Cython-0.29.13.dist-info/\n",
    "cython.py\n",
    "cytoolz/\n",
    "cytoolz-0.10.0-py3.7.egg-info/\n",
    "dask/\n",
    "dask-2.5.2.dist-info/\n",
    "dataclasses-0.6.dist-info/\n",
    "dataclasses.py\n",
    "dateutil/\n",
    "decorator-4.4.0.dist-info/\n",
    "decorator.py\n",
    "defusedxml/\n",
    "defusedxml-0.6.0-py2.7.egg-info/\n",
    "dicom/\n",
    "dicom-0.9.9.post1.dist-info/\n",
    "dicom.egg-info/\n",
    "dicom.py\n",
    "dill/\n",
    "dill-0.3.2.dist-info/\n",
    "distributed/\n",
    "distributed-2.5.2.dist-info/\n",
    "dm_tree-0.1.5.dist-info/\n",
    "docs/\n",
    "docutils/\n",
    "docutils-0.15.2.dist-info/\n",
    "easy_install.py\n",
    "entrypoints-0.3-py3.7.egg-info\n",
    "entrypoints.py\n",
    "erlastic/\n",
    "erlastic-2.0.0.dist-info/\n",
    "et_xmlfile/\n",
    "et_xmlfile-1.0.1-py3.7.egg-info/\n",
    "fastcache/\n",
    "fastcache-1.1.0.dist-info/\n",
    "filelock-3.0.12.dist-info/\n",
    "filelock.py\n",
    "flask/\n",
    "Flask-1.1.1.dist-info/\n",
    "_foo.cpython-37m-x86_64-linux-gnu.so*\n",
    "fsspec/\n",
    "fsspec-0.5.2.dist-info/\n",
    "future/\n",
    "future-0.17.1-py3.7.egg-info/\n",
    "gast/\n",
    "gast-0.3.3.dist-info/\n",
    "gevent/\n",
    "gevent-1.4.0-py3.7.egg-info/\n",
    "gin/\n",
    "gin_config-0.3.0.dist-info/\n",
    "glob2/\n",
    "glob2-0.7.dist-info/\n",
    "gmpy2-2.0.8-py3.7.egg-info\n",
    "gmpy2.cpython-37m-x86_64-linux-gnu.so*\n",
    "google/\n",
    "googleapiclient/\n",
    "google_api_core-1.21.0.dist-info/\n",
    "google_api_core-1.21.0-py3.8-nspkg.pth\n",
    "google_api_python_client-1.9.3.dist-info/\n",
    "googleapis_common_protos-1.52.0.dist-info/\n",
    "googleapis_common_protos-1.52.0-py3.8-nspkg.pth\n",
    "google_auth-1.18.0.dist-info/\n",
    "google_auth-1.18.0-py3.8-nspkg.pth\n",
    "google_auth_httplib2-0.0.3.dist-info/\n",
    "google_auth_httplib2.py\n",
    "google_auth_oauthlib/\n",
    "google_auth_oauthlib-0.4.1.dist-info/\n",
    "google_cloud_bigquery-1.25.0.dist-info/\n",
    "google_cloud_bigquery-1.25.0-py3.8-nspkg.pth\n",
    "google_cloud_core-1.3.0.dist-info/\n",
    "google_cloud_core-1.3.0-py3.8-nspkg.pth\n",
    "google_pasta-0.2.0.dist-info/\n",
    "google_resumable_media-0.5.1.dist-info/\n",
    "google_resumable_media-0.5.1-py3.8-nspkg.pth\n",
    "GPUtil/\n",
    "GPUtil-1.4.0.dist-info/\n",
    "greenlet-0.4.15.dist-info/\n",
    "greenlet.cpython-37m-x86_64-linux-gnu.so*\n",
    "grpc/\n",
    "grpcio-1.30.0.dist-info/\n",
    "h5py/\n",
    "h5py-2.10.0.dist-info/\n",
    "HeapDict-1.0.1.dist-info/\n",
    "heapdict.py\n",
    "html5lib/\n",
    "html5lib-1.0.1.dist-info/\n",
    "httplib2/\n",
    "httplib2-0.18.1.dist-info/\n",
    "idna/\n",
    "idna-2.10.dist-info/\n",
    "imageio/\n",
    "imageio-2.6.0.dist-info/\n",
    "imagesize-1.1.0-py3.7.egg-info/\n",
    "imagesize.py\n",
    "importlib_metadata/\n",
    "importlib_metadata-1.7.0.dist-info/\n",
    "ipykernel/\n",
    "ipykernel-5.1.2.dist-info/\n",
    "ipykernel_launcher.py\n",
    "IPython/\n",
    "ipython-7.8.0.dist-info/\n",
    "ipython_genutils/\n",
    "ipython_genutils-0.2.0-py3.7.egg-info\n",
    "ipywidgets/\n",
    "ipywidgets-7.5.1.dist-info/\n",
    "isort/\n",
    "isort-4.3.21.dist-info/\n",
    "isympy.py\n",
    "itsdangerous/\n",
    "itsdangerous-1.1.0.dist-info/\n",
    "j\n",
    "jdcal-1.4.1.dist-info/\n",
    "jdcal.py\n",
    "jedi/\n",
    "jedi-0.15.1.dist-info/\n",
    "jeepney/\n",
    "jeepney-0.4.1.dist-info/\n",
    "jinja2/\n",
    "Jinja2-2.10.3.dist-info/\n",
    "jmespath/\n",
    "jmespath-0.10.0.dist-info/\n",
    "joblib/\n",
    "joblib-0.13.2-py3.7.egg-info/\n",
    "json5/\n",
    "json5-0.8.5.dist-info/\n",
    "jsonschema/\n",
    "jsonschema-3.0.2.dist-info/\n",
    "jupyter-1.0.0.dist-info/\n",
    "jupyter_client/\n",
    "jupyter_client-5.3.3.dist-info/\n",
    "jupyter_console/\n",
    "jupyter_console-6.0.0-py3.7.egg-info/\n",
    "jupyter_contrib_core/\n",
    "jupyter_contrib_core-0.3.3-py2.7.egg-info/\n",
    "jupyter_contrib_nbextensions/\n",
    "jupyter_contrib_nbextensions-0.5.1-py3.7.egg-info/\n",
    "jupyter_core/\n",
    "jupyter_core-4.5.0.dist-info/\n",
    "jupyter_highlight_selected_word/\n",
    "jupyter_highlight_selected_word-0.2.0-py3.7.egg-info/\n",
    "jupyterlab/\n",
    "jupyterlab-1.1.4-py3.7.egg-info/\n",
    "jupyterlab_server/\n",
    "jupyterlab_server-1.0.6.dist-info/\n",
    "jupyter_latex_envs-1.4.6.dist-info/\n",
    "jupyter_nbextensions_configurator/\n",
    "jupyter_nbextensions_configurator-0.4.1-py3.7.egg-info/\n",
    "jupyter.py\n",
    "kaggle/\n",
    "kaggle-1.5.6.dist-info/\n",
    "keras/\n",
    "Keras-2.4.3.dist-info/\n",
    "keras_applications/\n",
    "Keras_Applications-1.0.8.dist-info/\n",
    "keras_preprocessing/\n",
    "Keras_Preprocessing-1.1.2.dist-info/\n",
    "keyring/\n",
    "keyring-18.0.0.dist-info/\n",
    "kiwisolver-1.1.0.dist-info/\n",
    "kiwisolver.cpython-37m-x86_64-linux-gnu.so*\n",
    "latex_envs/\n",
    "lazy_object_proxy/\n",
    "lazy_object_proxy-1.4.2.dist-info/\n",
    "libarchive/\n",
    "libarchive_c-2.8-py3.7.egg-info/\n",
    "libfuturize/\n",
    "libpasteurize/\n",
    "lief/\n",
    "lief-0.9.0-py3.7.egg-info/\n",
    "llvmlite/\n",
    "llvmlite-0.29.0-py3.7.egg-info\n",
    "locket/\n",
    "locket-0.2.0-py3.7.egg-info\n",
    "lxml/\n",
    "lxml-4.4.1-py3.7.egg-info/\n",
    "markdown/\n",
    "Markdown-3.2.2.dist-info/\n",
    "markupsafe/\n",
    "MarkupSafe-1.1.1.dist-info/\n",
    "matplotlib/\n",
    "matplotlib-3.1.1-py3.7.egg-info/\n",
    "matplotlib-3.1.1-py3.7-nspkg.pth\n",
    "mccabe-0.6.1-py3.7.egg-info/\n",
    "mccabe.py\n",
    "mistune-0.8.4.dist-info/\n",
    "mistune.py\n",
    "mkl/\n",
    "mkl_fft/\n",
    "mkl_fft-1.0.14-py3.7.egg-info/\n",
    "mkl_random/\n",
    "mkl_random-1.1.0.dist-info/\n",
    "mkl_service-2.3.0-py3.7.egg-info/\n",
    "mock/\n",
    "mock-3.0.5.dist-info/\n",
    "more_itertools/\n",
    "more_itertools-7.2.0.dist-info/\n",
    "mpl_toolkits/\n",
    "mpmath/\n",
    "mpmath-1.1.0-py3.7.egg-info\n",
    "msgpack/\n",
    "msgpack-0.6.1.dist-info/\n",
    "multipledispatch/\n",
    "multipledispatch-0.6.0-py3.7.egg-info/\n",
    "navigator_updater/\n",
    "navigator_updater-0.2.1-py3.7.egg-info/\n",
    "nbconvert/\n",
    "nbconvert-5.6.0.dist-info/\n",
    "nbformat/\n",
    "nbformat-4.4.0.dist-info/\n",
    "networkx/\n",
    "networkx-2.3.dist-info/\n",
    "nltk/\n",
    "nltk-3.4.5.dist-info/\n",
    "nose/\n",
    "nose-1.3.7-py3.7.egg-info/\n",
    "notebook/\n",
    "notebook-6.0.1.dist-info/\n",
    "numba/\n",
    "numba-0.45.1-py3.7.egg-info/\n",
    "numexpr/\n",
    "numexpr-2.7.0-py3.7.egg-info/\n",
    "numpy/\n",
    "numpy-1.19.0.dist-info/\n",
    "numpydoc/\n",
    "numpydoc-0.9.1.dist-info/\n",
    "numpy.libs/\n",
    "oauth2client/\n",
    "oauth2client-4.1.3.dist-info/\n",
    "oauthlib/\n",
    "oauthlib-3.1.0.dist-info/\n",
    "official/\n",
    "olefile/\n",
    "olefile-0.46-py3.7.egg-info/\n",
    "opencv_python_headless-4.2.0.34.dist-info/\n",
    "openpyxl/\n",
    "openpyxl-3.0.0.dist-info/\n",
    "OpenSSL/\n",
    "opt_einsum/\n",
    "opt_einsum-3.2.1.dist-info/\n",
    "packaging/\n",
    "packaging-19.2.dist-info/\n",
    "pandas/\n",
    "pandas-0.25.1.dist-info/\n",
    "pandocfilters-1.4.2.dist-info/\n",
    "pandocfilters.py\n",
    "parso/\n",
    "parso-0.5.1.dist-info/\n",
    "partd/\n",
    "partd-1.0.0.dist-info/\n",
    "past/\n",
    "pasta/\n",
    "path/\n",
    "pathlib2/\n",
    "pathlib2-2.3.5.dist-info/\n",
    "path.py-12.0.1.dist-info/\n",
    "patsy/\n",
    "patsy-0.5.1-py3.7.egg-info/\n",
    "pep8-1.7.1-py3.7.egg-info/\n",
    "pep8.py\n",
    "pexpect/\n",
    "pexpect-4.7.0.dist-info/\n",
    "pickleshare-0.7.5-py3.7.egg-info/\n",
    "pickleshare.py\n",
    "PIL/\n",
    "Pillow-6.2.0.dist-info/\n",
    "pip/\n",
    "pip-20.1.1.dist-info/\n",
    "pkginfo/\n",
    "pkginfo-1.5.0.1-py3.7.egg-info/\n",
    "pkg_resources/\n",
    "pluggy/\n",
    "pluggy-0.13.0.dist-info/\n",
    "ply/\n",
    "ply-3.11-py3.7.egg-info/\n",
    "prometheus_client/\n",
    "prometheus_client-0.7.1.dist-info/\n",
    "promise/\n",
    "promise-2.3.dist-info/\n",
    "prompt_toolkit/\n",
    "prompt_toolkit-2.0.10.dist-info/\n",
    "protobuf-3.12.2.dist-info/\n",
    "protobuf-3.12.2-py3.7-nspkg.pth\n",
    "psutil/\n",
    "psutil-5.6.3.dist-info/\n",
    "ptyprocess/\n",
    "ptyprocess-0.6.0-py3.7.egg-info\n",
    "pvectorc.cpython-37m-x86_64-linux-gnu.so*\n",
    "py/\n",
    "py-1.8.0.dist-info/\n",
    "pyasn1/\n",
    "pyasn1-0.4.8.dist-info/\n",
    "pyasn1_modules/\n",
    "pyasn1_modules-0.2.8.dist-info/\n",
    "__pycache__/\n",
    "pycodestyle-2.5.0-py3.7.egg-info/\n",
    "pycodestyle.py\n",
    "pycosat-0.6.3-py3.7.egg-info\n",
    "pycosat.cpython-37m-x86_64-linux-gnu.so*\n",
    "pycparser/\n",
    "pycparser-2.19-py3.7.egg-info/\n",
    "py_cpuinfo-7.0.0.dist-info/\n",
    "pycrypto-2.6.1-py3.7.egg-info\n",
    "pycurl-7.43.0.3-py3.7.egg-info\n",
    "pycurl.cpython-37m-x86_64-linux-gnu.so*\n",
    "pydicom/\n",
    "pydicom-2.0.0.dist-info/\n",
    "pyflakes/\n",
    "pyflakes-2.1.1.dist-info/\n",
    "pygments/\n",
    "Pygments-2.4.2.dist-info/\n",
    "pylab.py\n",
    "_pylief.cpython-37m-x86_64-linux-gnu.so\n",
    "pylint/\n",
    "pylint-2.4.2.dist-info/\n",
    "pyodbc-4.0.27.dist-info/\n",
    "pyodbc.cpython-37m-x86_64-linux-gnu.so*\n",
    "pyOpenSSL-19.0.0-py3.7.egg-info/\n",
    "pyparsing-2.4.2.dist-info/\n",
    "pyparsing.py\n",
    "PyQt5/\n",
    "pyrsistent/\n",
    "pyrsistent-0.15.4.dist-info/\n",
    "_pyrsistent_version.py\n",
    "PySocks-1.7.1.dist-info/\n",
    "_pytest/\n",
    "pytest-5.2.1-py3.7.egg-info/\n",
    "pytest_arraydiff/\n",
    "pytest_arraydiff-0.3.dist-info/\n",
    "pytest_astropy-0.5.0.dist-info/\n",
    "pytest_doctestplus/\n",
    "pytest_doctestplus-0.4.0.dist-info/\n",
    "pytest_openfiles/\n",
    "pytest_openfiles-0.4.0.dist-info/\n",
    "pytest.py\n",
    "pytest_remotedata/\n",
    "pytest_remotedata-0.3.2.dist-info/\n",
    "python_dateutil-2.8.0.dist-info/\n",
    "python_slugify-4.0.1.dist-info/\n",
    "pytorch_pretrained_bert/\n",
    "pytorch_pretrained_bert-0.6.2.dist-info/\n",
    "pytz/\n",
    "pytz-2019.3.dist-info/\n",
    "PyWavelets-1.0.3.dist-info/\n",
    "pywt/\n",
    "pyximport/\n",
    "PyYAML-5.1.2-py3.7.egg-info\n",
    "pyzmq-18.1.0-py3.7.egg-info/\n",
    "qtawesome/\n",
    "QtAwesome-0.6.0.dist-info/\n",
    "qtconsole/\n",
    "qtconsole-4.5.5.dist-info/\n",
    "qtpy/\n",
    "QtPy-1.9.0.dist-info/\n",
    "README.md\n",
    "README.txt\n",
    "regex/\n",
    "regex-2020.6.8.dist-info/\n",
    "report.txt\n",
    "requests/\n",
    "requests-2.24.0.dist-info/\n",
    "requests_oauthlib/\n",
    "requests_oauthlib-1.3.0.dist-info/\n",
    "rope/\n",
    "rope-0.14.0-py2.7.egg-info/\n",
    "rsa/\n",
    "rsa-4.6.dist-info/\n",
    "ruamel_yaml/\n",
    "ruamel_yaml-0.15.46-py3.7.egg-info\n",
    "s3transfer/\n",
    "s3transfer-0.3.3.dist-info/\n",
    "scikit_image-0.15.0.dist-info/\n",
    "scikit_learn-0.21.3.dist-info/\n",
    "scipy/\n",
    "scipy-1.4.1.dist-info/\n",
    "scripts/\n",
    "seaborn/\n",
    "seaborn-0.9.0.dist-info/\n",
    "secretstorage/\n",
    "SecretStorage-3.1.1-py3.7.egg-info/\n",
    "send2trash/\n",
    "Send2Trash-1.5.0-py3.7.egg-info/\n",
    "sentencepiece-0.1.91.dist-info/\n",
    "_sentencepiece.cpython-37m-x86_64-linux-gnu.so*\n",
    "sentencepiece.py\n",
    "seqeval/\n",
    "seqeval-0.0.12.dist-info/\n",
    "setuptools/\n",
    "setuptools-49.1.1.dist-info/\n",
    "setuptools.pth\n",
    "simplegeneric-0.8.1-py3.7.egg-info/\n",
    "simplegeneric.py\n",
    "singledispatch-3.4.0.3-py3.7.egg-info/\n",
    "singledispatch_helpers.py\n",
    "singledispatch.py\n",
    "sipconfig.py\n",
    "sipdistutils.py\n",
    "sip.pyi\n",
    "sip.so*\n",
    "six-1.15.0.dist-info/\n",
    "six.py\n",
    "skimage/\n",
    "sklearn/\n",
    "slugify/\n",
    "snowballstemmer/\n",
    "snowballstemmer-2.0.0.dist-info/\n",
    "sockshandler.py\n",
    "socks.py\n",
    "sortedcollections/\n",
    "sortedcollections-1.1.2.dist-info/\n",
    "sortedcontainers/\n",
    "sortedcontainers-2.1.0-py3.7.egg-info/\n",
    "soupsieve/\n",
    "soupsieve-1.9.3.dist-info/\n",
    "sphinx/\n",
    "Sphinx-2.2.0.dist-info/\n",
    "sphinxcontrib/\n",
    "sphinxcontrib_applehelp-1.0.1.dist-info/\n",
    "sphinxcontrib_applehelp-1.0.1-py3.7-nspkg.pth\n",
    "sphinxcontrib_devhelp-1.0.1.dist-info/\n",
    "sphinxcontrib_devhelp-1.0.1-py3.7-nspkg.pth\n",
    "sphinxcontrib_htmlhelp-1.0.2.dist-info/\n",
    "sphinxcontrib_htmlhelp-1.0.2-py3.7-nspkg.pth\n",
    "sphinxcontrib_jsmath-1.0.1.dist-info/\n",
    "sphinxcontrib_jsmath-1.0.1-py3.7-nspkg.pth\n",
    "sphinxcontrib_qthelp-1.0.2.dist-info/\n",
    "sphinxcontrib_qthelp-1.0.2-py3.7-nspkg.pth\n",
    "sphinxcontrib_serializinghtml-1.1.3.dist-info/\n",
    "sphinxcontrib_serializinghtml-1.1.3-py3.7-nspkg.pth\n",
    "sphinxcontrib_websupport-1.1.2.dist-info/\n",
    "sphinxcontrib_websupport-1.1.2-py2.7-nspkg.pth\n",
    "spyder/\n",
    "spyder-3.3.6.dist-info/\n",
    "spyder_breakpoints/\n",
    "spyder_io_dcm/\n",
    "spyder_io_hdf5/\n",
    "spyder_kernels/\n",
    "spyder_kernels-0.5.2.dist-info/\n",
    "spyder_profiler/\n",
    "spyder_pylint/\n",
    "sqlalchemy/\n",
    "SQLAlchemy-1.3.9.dist-info/\n",
    "statsmodels/\n",
    "statsmodels-0.10.1.dist-info/\n",
    "sympy/\n",
    "sympy-1.4-py3.7.egg-info/\n",
    "tables/\n",
    "tables-3.5.2.dist-info/\n",
    "tblib/\n",
    "tblib-1.4.0.dist-info/\n",
    "tb_nightly-2.3.0a20200706.dist-info/\n",
    "tensorboard/\n",
    "tensorboard-1.13.1.dist-info/\n",
    "tensorboard_plugin_wit/\n",
    "tensorboard_plugin_wit-1.7.0.dist-info/\n",
    "tensorflow/\n",
    "tensorflow-1.13.1.dist-info/\n",
    "tensorflow_addons/\n",
    "tensorflow_addons-0.10.0.dist-info/\n",
    "tensorflow_datasets/\n",
    "tensorflow_datasets-3.1.0.dist-info/\n",
    "tensorflow_estimator/\n",
    "tensorflow_estimator-1.13.0.dist-info/\n",
    "tensorflow_gpu-2.2.0.dist-info/\n",
    "tensorflow_hub/\n",
    "tensorflow_hub-0.8.0.dist-info/\n",
    "tensorflow_metadata/\n",
    "tensorflow_metadata-0.22.2.dist-info/\n",
    "tensorflow_model_optimization/\n",
    "tensorflow_model_optimization-0.3.0.dist-info/\n",
    "termcolor-1.1.0.dist-info/\n",
    "termcolor.py\n",
    "terminado/\n",
    "terminado-0.8.2-py3.7.egg-info\n",
    "test_data/\n",
    "testpath/\n",
    "testpath-0.4.2.dist-info/\n",
    "test_pycosat.py\n",
    "tests/\n",
    "text_unidecode/\n",
    "text_unidecode-1.3.dist-info/\n",
    "tf_estimator_nightly-2.4.0.dev2020070601.dist-info/\n",
    "tf_models_nightly-2.2.0.dev20200706.dist-info/\n",
    "tf_nightly-2.4.0.dev20200706.dist-info/\n",
    "tf_nightly_gpu-2.4.0.dev20200707.dist-info/\n",
    "tf_slim/\n",
    "tf_slim-1.1.0.dist-info/\n",
    "tlz/\n",
    "toolz/\n",
    "toolz-0.10.0.dist-info/\n",
    "torch/\n",
    "torch-1.5.1.dist-info/\n",
    "tornado/\n",
    "tornado-6.0.3.dist-info/\n",
    "tqdm/\n",
    "tqdm-4.36.1.dist-info/\n",
    "traitlets/\n",
    "traitlets-4.3.3.dist-info/\n",
    "tree/\n",
    "typeguard/\n",
    "typeguard-2.9.1.dist-info/\n",
    "typing-3.7.4.1.dist-info/\n",
    "typing.py\n",
    "uncased_L-24_H-1024_A-16/\n",
    "unicodecsv/\n",
    "unicodecsv-0.14.1-py3.7.egg-info/\n",
    "uritemplate/\n",
    "uritemplate-3.0.1.dist-info/\n",
    "urllib3/\n",
    "urllib3-1.25.9.dist-info/\n",
    "wcwidth/\n",
    "wcwidth-0.1.7-py3.7.egg-info/\n",
    "webencodings/\n",
    "webencodings-0.5.1-py3.7.egg-info/\n",
    "werkzeug/\n",
    "Werkzeug-1.0.1.dist-info/\n",
    "wheel/\n",
    "wheel-0.34.2.dist-info/\n",
    "widgetsnbextension/\n",
    "widgetsnbextension-3.5.1.dist-info/\n",
    "wrapt/\n",
    "wrapt-1.12.1.dist-info/\n",
    "wurlitzer-1.0.3.dist-info/\n",
    "wurlitzer.py\n",
    "xlrd/\n",
    "xlrd-1.2.0.dist-info/\n",
    "xlsxwriter/\n",
    "XlsxWriter-1.2.1.dist-info/\n",
    "xlwt/\n",
    "xlwt-1.3.0-py3.7.egg-info/\n",
    "xontrib/\n",
    "yaml/\n",
    "_yaml.cpython-37m-x86_64-linux-gnu.so*\n",
    "zict/\n",
    "zict-1.0.0-py2.7.egg-info/\n",
    "zipp-3.1.0.dist-info/\n",
    "zipp.py\n",
    "zmq/\n",
    "\n",
    "import tensorflow as tf\n",
    "physical_devices = tf.config.experimental.list_physical_devices('GPU')\n",
    "tf.config.experimental.set_memory_growth(physical_devices[0], True)\n",
    "\n",
    "---------------------------------------------------------------------------\n",
    "AttributeError                            Traceback (most recent call last)\n",
    "<ipython-input-7-3141dce84fad> in <module>\n",
    "----> 1 import tensorflow as tf\n",
    "      2 physical_devices = tf.config.experimental.list_physical_devices('GPU')\n",
    "      3 tf.config.experimental.set_memory_growth(physical_devices[0], True)\n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/tensorflow/__init__.py in <module>\n",
    "     39 import sys as _sys\n",
    "     40 \n",
    "---> 41 from tensorflow.python.tools import module_util as _module_util\n",
    "     42 from tensorflow.python.util.lazy_loader import LazyLoader as _LazyLoader\n",
    "     43 \n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/tensorflow/python/__init__.py in <module>\n",
    "     82 from tensorflow.python import data\n",
    "     83 from tensorflow.python import distribute\n",
    "---> 84 from tensorflow.python import keras\n",
    "     85 from tensorflow.python.feature_column import feature_column_lib as feature_column\n",
    "     86 from tensorflow.python.layers import layers\n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/__init__.py in <module>\n",
    "     25 \n",
    "     26 # See b/110718070#comment18 for more details about this import.\n",
    "---> 27 from tensorflow.python.keras import models\n",
    "     28 \n",
    "     29 from tensorflow.python.keras.engine.input_layer import Input\n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/models.py in <module>\n",
    "     22 from tensorflow.python.framework import ops\n",
    "     23 from tensorflow.python.keras import backend as K\n",
    "---> 24 from tensorflow.python.keras import metrics as metrics_module\n",
    "     25 from tensorflow.python.keras import optimizers\n",
    "     26 from tensorflow.python.keras.engine import network\n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/metrics.py in <module>\n",
    "     35 from tensorflow.python.framework import tensor_spec\n",
    "     36 from tensorflow.python.keras import backend as K\n",
    "---> 37 from tensorflow.python.keras.engine import base_layer\n",
    "     38 from tensorflow.python.keras.engine import base_layer_utils\n",
    "     39 from tensorflow.python.keras.losses import binary_crossentropy\n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py in <module>\n",
    "     49 from tensorflow.python.keras import backend\n",
    "     50 from tensorflow.python.keras import constraints\n",
    "---> 51 from tensorflow.python.keras import initializers\n",
    "     52 from tensorflow.python.keras import regularizers\n",
    "     53 from tensorflow.python.keras.engine import base_layer_utils\n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/initializers/__init__.py in <module>\n",
    "    125 # from ALL_OBJECTS. We make no guarantees as to whether these objects will\n",
    "    126 # using their correct version.\n",
    "--> 127 populate_deserializable_objects()\n",
    "    128 globals().update(LOCAL.ALL_OBJECTS)\n",
    "    129 \n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/initializers/__init__.py in populate_deserializable_objects()\n",
    "     83     v2_objs = {}\n",
    "     84     base_cls = initializers_v2.Initializer\n",
    "---> 85     generic_utils.populate_dict_with_module_objects(\n",
    "     86         v2_objs,\n",
    "     87         [initializers_v2],\n",
    "\n",
    "AttributeError: module 'tensorflow.python.keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'\n",
    "\n",
    "#import tensorflow as tf\n",
    "from tensorflow import keras\n",
    "\n",
    "config = tf.compat.v1.ConfigProto()\n",
    "config.gpu_options.allow_growth = True\n",
    "sess = tf.Session(config=config)\n",
    "\n",
    "---------------------------------------------------------------------------\n",
    "AttributeError                            Traceback (most recent call last)\n",
    "<ipython-input-6-bc61f24dae51> in <module>\n",
    "      1 #import tensorflow as tf\n",
    "----> 2 from tensorflow import keras\n",
    "      3 \n",
    "      4 config = tf.compat.v1.ConfigProto()\n",
    "      5 config.gpu_options.allow_growth = True\n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/tensorflow/__init__.py in <module>\n",
    "     39 import sys as _sys\n",
    "     40 \n",
    "---> 41 from tensorflow.python.tools import module_util as _module_util\n",
    "     42 from tensorflow.python.util.lazy_loader import LazyLoader as _LazyLoader\n",
    "     43 \n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/tensorflow/python/__init__.py in <module>\n",
    "     82 from tensorflow.python import data\n",
    "     83 from tensorflow.python import distribute\n",
    "---> 84 from tensorflow.python import keras\n",
    "     85 from tensorflow.python.feature_column import feature_column_lib as feature_column\n",
    "     86 from tensorflow.python.layers import layers\n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/__init__.py in <module>\n",
    "     25 \n",
    "     26 # See b/110718070#comment18 for more details about this import.\n",
    "---> 27 from tensorflow.python.keras import models\n",
    "     28 \n",
    "     29 from tensorflow.python.keras.engine.input_layer import Input\n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/models.py in <module>\n",
    "     22 from tensorflow.python.framework import ops\n",
    "     23 from tensorflow.python.keras import backend as K\n",
    "---> 24 from tensorflow.python.keras import metrics as metrics_module\n",
    "     25 from tensorflow.python.keras import optimizers\n",
    "     26 from tensorflow.python.keras.engine import network\n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/metrics.py in <module>\n",
    "     35 from tensorflow.python.framework import tensor_spec\n",
    "     36 from tensorflow.python.keras import backend as K\n",
    "---> 37 from tensorflow.python.keras.engine import base_layer\n",
    "     38 from tensorflow.python.keras.engine import base_layer_utils\n",
    "     39 from tensorflow.python.keras.losses import binary_crossentropy\n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py in <module>\n",
    "     49 from tensorflow.python.keras import backend\n",
    "     50 from tensorflow.python.keras import constraints\n",
    "---> 51 from tensorflow.python.keras import initializers\n",
    "     52 from tensorflow.python.keras import regularizers\n",
    "     53 from tensorflow.python.keras.engine import base_layer_utils\n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/initializers/__init__.py in <module>\n",
    "    125 # from ALL_OBJECTS. We make no guarantees as to whether these objects will\n",
    "    126 # using their correct version.\n",
    "--> 127 populate_deserializable_objects()\n",
    "    128 globals().update(LOCAL.ALL_OBJECTS)\n",
    "    129 \n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/initializers/__init__.py in populate_deserializable_objects()\n",
    "     83     v2_objs = {}\n",
    "     84     base_cls = initializers_v2.Initializer\n",
    "---> 85     generic_utils.populate_dict_with_module_objects(\n",
    "     86         v2_objs,\n",
    "     87         [initializers_v2],\n",
    "\n",
    "AttributeError: module 'tensorflow.python.keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'\n",
    "\n",
    "!pip install https://storage.googleapis.com/bert_models/2018_11_23/multi_cased_L-12_H-768_A-12.zip\n",
    "\n",
    "Collecting https://storage.googleapis.com/bert_models/2018_11_23/multi_cased_L-12_H-768_A-12.zip\n",
    "  Using cached https://storage.googleapis.com/bert_models/2018_11_23/multi_cased_L-12_H-768_A-12.zip (662.9 MB)\n",
    "    ERROR: Command errored out with exit status 1:\n",
    "     command: /home/ubuntu/virt-env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-req-build-pat2nar8/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-req-build-pat2nar8/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-md3sygo6\n",
    "         cwd: /tmp/pip-req-build-pat2nar8/\n",
    "    Complete output (5 lines):\n",
    "    Traceback (most recent call last):\n",
    "      File \"<string>\", line 1, in <module>\n",
    "      File \"/usr/lib/python3.6/tokenize.py\", line 452, in open\n",
    "        buffer = _builtin_open(filename, 'rb')\n",
    "    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-pat2nar8/setup.py'\n",
    "    ----------------------------------------\n",
    "ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
    "\n",
    "pip install --no-cache-dir https://storage.googleapis.com/bert_models/2018_11_23/multi_cased_L-12_H-768_A-12.zip\n",
    "\n",
    "Collecting https://storage.googleapis.com/bert_models/2018_11_23/multi_cased_L-12_H-768_A-12.zip\n",
    "  Downloading https://storage.googleapis.com/bert_models/2018_11_23/multi_cased_L-12_H-768_A-12.zip (662.9 MB)\n",
    "     |████████████████████████████████| 662.9 MB 54.2 MB/s eta 0:00:011 |▍                               | 8.8 MB 1.8 MB/s eta 0:06:02     |█▏                              | 24.3 MB 30.8 MB/s eta 0:00:21     |██████████▌                     | 218.6 MB 53.0 MB/s eta 0:00:09�███████▉            | 411.2 MB 104.3 MB/s eta 0:00:03��███████████████████▋           | 428.0 MB 101.6 MB/s eta 0:00:03\n",
    "    ERROR: Command errored out with exit status 1:\n",
    "     command: /home/ubuntu/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-req-build-5y9i5u_7/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-req-build-5y9i5u_7/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /tmp/pip-pip-egg-info-wc4l6910\n",
    "         cwd: /tmp/pip-req-build-5y9i5u_7/\n",
    "    Complete output (5 lines):\n",
    "    Traceback (most recent call last):\n",
    "      File \"<string>\", line 1, in <module>\n",
    "      File \"/home/ubuntu/anaconda3/lib/python3.7/tokenize.py\", line 447, in open\n",
    "        buffer = _builtin_open(filename, 'rb')\n",
    "    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-5y9i5u_7/setup.py'\n",
    "    ----------------------------------------\n",
    "ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
    "Note: you may need to restart the kernel to use updated packages.\n",
    "\n",
    "pip install --upgrade --force-reinstall tensorflow-gpu\n",
    "\n",
    "Collecting tensorflow-gpu\n",
    "  Downloading tensorflow_gpu-2.2.0-cp37-cp37m-manylinux2010_x86_64.whl (516.2 MB)\n",
    "     |████████████████████████████████| 516.2 MB 3.6 kB/s  eta 0:00:01    |███▋                            | 58.8 MB 21.0 MB/s eta 0:00:22     |████▋                           | 74.2 MB 14.6 MB/s eta 0:00:31     |███████                         | 112.0 MB 23.9 MB/s eta 0:00:17     |███████▎                        | 116.7 MB 23.9 MB/s eta 0:00:17     |███████▉                        | 127.2 MB 23.9 MB/s eta 0:00:17     |██████████▌                     | 168.8 MB 26.3 MB/s eta 0:00:14     |█████████████▎                  | 213.8 MB 37.1 MB/s eta 0:00:09     |█████████████▍                  | 215.8 MB 37.1 MB/s eta 0:00:09     |████████████████▌               | 265.4 MB 56.2 MB/s eta 0:00:05     |█████████████████████████████▎  | 471.9 MB 80.3 MB/s eta 0:00:01\n",
    "Collecting wrapt>=1.11.1\n",
    "  Downloading wrapt-1.12.1.tar.gz (27 kB)\n",
    "Collecting gast==0.3.3\n",
    "  Using cached gast-0.3.3-py2.py3-none-any.whl (9.7 kB)\n",
    "Processing /home/ubuntu/.cache/pip/wheels/7c/06/54/bc84598ba1daf8f970247f550b175aaaee85f68b4b0c5ab2c6/termcolor-1.1.0-cp37-none-any.whl\n",
    "Collecting grpcio>=1.8.6\n",
    "  Using cached grpcio-1.30.0-cp37-cp37m-manylinux2010_x86_64.whl (3.0 MB)\n",
    "Collecting numpy<2.0,>=1.16.0\n",
    "  Downloading numpy-1.19.0-cp37-cp37m-manylinux2010_x86_64.whl (14.6 MB)\n",
    "     |████████████████████████████████| 14.6 MB 29.9 MB/s eta 0:00:01    |█████▎                          | 2.4 MB 29.9 MB/s eta 0:00:01\n",
    "Collecting wheel>=0.26; python_version >= \"3\"\n",
    "  Downloading wheel-0.34.2-py2.py3-none-any.whl (26 kB)\n",
    "Collecting tensorboard<2.3.0,>=2.2.0\n",
    "  Using cached tensorboard-2.2.2-py3-none-any.whl (3.0 MB)\n",
    "Collecting h5py<2.11.0,>=2.10.0\n",
    "  Using cached h5py-2.10.0-cp37-cp37m-manylinux1_x86_64.whl (2.9 MB)\n",
    "Processing /home/ubuntu/.cache/pip/wheels/8e/28/49/fad4e7f0b9a1227708cbbee4487ac8558a7334849cb81c813d/absl_py-0.9.0-cp37-none-any.whl\n",
    "Collecting opt-einsum>=2.3.2\n",
    "  Using cached opt_einsum-3.2.1-py3-none-any.whl (63 kB)\n",
    "Collecting google-pasta>=0.1.8\n",
    "  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)\n",
    "Collecting six>=1.12.0\n",
    "  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)\n",
    "Collecting tensorflow-estimator<2.3.0,>=2.2.0\n",
    "  Using cached tensorflow_estimator-2.2.0-py2.py3-none-any.whl (454 kB)\n",
    "Collecting scipy==1.4.1; python_version >= \"3\"\n",
    "  Using cached scipy-1.4.1-cp37-cp37m-manylinux1_x86_64.whl (26.1 MB)\n",
    "Collecting protobuf>=3.8.0\n",
    "  Using cached protobuf-3.12.2-cp37-cp37m-manylinux1_x86_64.whl (1.3 MB)\n",
    "Collecting astunparse==1.6.3\n",
    "  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)\n",
    "Collecting keras-preprocessing>=1.1.0\n",
    "  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)\n",
    "Collecting markdown>=2.6.8\n",
    "  Using cached Markdown-3.2.2-py3-none-any.whl (88 kB)\n",
    "Collecting google-auth-oauthlib<0.5,>=0.4.1\n",
    "  Using cached google_auth_oauthlib-0.4.1-py2.py3-none-any.whl (18 kB)\n",
    "Collecting werkzeug>=0.11.15\n",
    "  Downloading Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)\n",
    "     |████████████████████████████████| 298 kB 33.4 MB/s eta 0:00:01\n",
    "Collecting setuptools>=41.0.0\n",
    "  Using cached setuptools-49.1.1-py3-none-any.whl (789 kB)\n",
    "Collecting google-auth<2,>=1.6.3\n",
    "  Using cached google_auth-1.18.0-py2.py3-none-any.whl (90 kB)\n",
    "Collecting tensorboard-plugin-wit>=1.6.0\n",
    "  Downloading tensorboard_plugin_wit-1.7.0-py3-none-any.whl (779 kB)\n",
    "     |████████████████████████████████| 779 kB 36.3 MB/s eta 0:00:01\n",
    "Collecting requests<3,>=2.21.0\n",
    "  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)\n",
    "Collecting importlib-metadata; python_version < \"3.8\"\n",
    "  Downloading importlib_metadata-1.7.0-py2.py3-none-any.whl (31 kB)\n",
    "Collecting requests-oauthlib>=0.7.0\n",
    "  Using cached requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)\n",
    "Collecting rsa<5,>=3.1.4; python_version >= \"3\"\n",
    "  Using cached rsa-4.6-py3-none-any.whl (47 kB)\n",
    "Collecting pyasn1-modules>=0.2.1\n",
    "  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)\n",
    "Collecting cachetools<5.0,>=2.0.0\n",
    "  Downloading cachetools-4.1.1-py3-none-any.whl (10 kB)\n",
    "Collecting chardet<4,>=3.0.2\n",
    "  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)\n",
    "Collecting certifi>=2017.4.17\n",
    "  Using cached certifi-2020.6.20-py2.py3-none-any.whl (156 kB)\n",
    "Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1\n",
    "  Using cached urllib3-1.25.9-py2.py3-none-any.whl (126 kB)\n",
    "Collecting idna<3,>=2.5\n",
    "  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)\n",
    "Collecting zipp>=0.5\n",
    "  Downloading zipp-3.1.0-py3-none-any.whl (4.9 kB)\n",
    "Collecting oauthlib>=3.0.0\n",
    "  Using cached oauthlib-3.1.0-py2.py3-none-any.whl (147 kB)\n",
    "Collecting pyasn1>=0.1.3\n",
    "  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)\n",
    "Building wheels for collected packages: wrapt\n",
    "  Building wheel for wrapt (setup.py) ... done\n",
    "  Created wheel for wrapt: filename=wrapt-1.12.1-cp37-cp37m-linux_x86_64.whl size=70960 sha256=ab9681a4c805349d85d5762e4645cfc3b0bea6f369531d3e33a6aee893ba5f06\n",
    "  Stored in directory: /home/ubuntu/.cache/pip/wheels/62/76/4c/aa25851149f3f6d9785f6c869387ad82b3fd37582fa8147ac6\n",
    "Successfully built wrapt\n",
    "ERROR: spyder 3.3.6 requires pyqt5<5.13; python_version >= \"3\", which is not installed.\n",
    "ERROR: spyder 3.3.6 requires pyqtwebengine<5.13; python_version >= \"3\", which is not installed.\n",
    "ERROR: astroid 2.3.1 requires typed-ast<1.5,>=1.4.0; implementation_name == \"cpython\" and python_version < \"3.8\", which is not installed.\n",
    "ERROR: tf-nightly 2.4.0.dev20200706 has requirement numpy<1.19.0,>=1.16.0, but you'll have numpy 1.19.0 which is incompatible.\n",
    "ERROR: tf-nightly-gpu 2.4.0.dev20200707 has requirement numpy<1.19.0,>=1.16.0, but you'll have numpy 1.19.0 which is incompatible.\n",
    "ERROR: kaggle 1.5.6 has requirement urllib3<1.25,>=1.21.1, but you'll have urllib3 1.25.9 which is incompatible.\n",
    "ERROR: astroid 2.3.1 has requirement six==1.12, but you'll have six 1.15.0 which is incompatible.\n",
    "ERROR: astroid 2.3.1 has requirement wrapt==1.11.*, but you'll have wrapt 1.12.1 which is incompatible.\n",
    "Installing collected packages: wrapt, gast, termcolor, six, grpcio, numpy, wheel, zipp, importlib-metadata, markdown, pyasn1, rsa, pyasn1-modules, cachetools, setuptools, google-auth, oauthlib, chardet, certifi, urllib3, idna, requests, requests-oauthlib, google-auth-oauthlib, werkzeug, absl-py, tensorboard-plugin-wit, protobuf, tensorboard, h5py, opt-einsum, google-pasta, tensorflow-estimator, scipy, astunparse, keras-preprocessing, tensorflow-gpu\n",
    "  Attempting uninstall: wrapt\n",
    "    Found existing installation: wrapt 1.11.2\n",
    "    Uninstalling wrapt-1.11.2:\n",
    "      Successfully uninstalled wrapt-1.11.2\n",
    "  Attempting uninstall: gast\n",
    "    Found existing installation: gast 0.3.3\n",
    "    Uninstalling gast-0.3.3:\n",
    "      Successfully uninstalled gast-0.3.3\n",
    "  Attempting uninstall: termcolor\n",
    "    Found existing installation: termcolor 1.1.0\n",
    "    Uninstalling termcolor-1.1.0:\n",
    "      Successfully uninstalled termcolor-1.1.0\n",
    "  Attempting uninstall: six\n",
    "    Found existing installation: six 1.12.0\n",
    "    Uninstalling six-1.12.0:\n",
    "      Successfully uninstalled six-1.12.0\n",
    "  Attempting uninstall: grpcio\n",
    "    Found existing installation: grpcio 1.30.0\n",
    "    Uninstalling grpcio-1.30.0:\n",
    "      Successfully uninstalled grpcio-1.30.0\n",
    "  Attempting uninstall: numpy\n",
    "    Found existing installation: numpy 1.17.2\n",
    "    Uninstalling numpy-1.17.2:\n",
    "      Successfully uninstalled numpy-1.17.2\n",
    "  Attempting uninstall: wheel\n",
    "    Found existing installation: wheel 0.33.6\n",
    "    Uninstalling wheel-0.33.6:\n",
    "      Successfully uninstalled wheel-0.33.6\n",
    "  Attempting uninstall: zipp\n",
    "    Found existing installation: zipp 0.6.0\n",
    "    Uninstalling zipp-0.6.0:\n",
    "      Successfully uninstalled zipp-0.6.0\n",
    "  Attempting uninstall: importlib-metadata\n",
    "    Found existing installation: importlib-metadata 0.23\n",
    "    Uninstalling importlib-metadata-0.23:\n",
    "      Successfully uninstalled importlib-metadata-0.23\n",
    "  Attempting uninstall: markdown\n",
    "    Found existing installation: Markdown 3.2.2\n",
    "    Uninstalling Markdown-3.2.2:\n",
    "      Successfully uninstalled Markdown-3.2.2\n",
    "  Attempting uninstall: pyasn1\n",
    "    Found existing installation: pyasn1 0.4.8\n",
    "    Uninstalling pyasn1-0.4.8:\n",
    "      Successfully uninstalled pyasn1-0.4.8\n",
    "  Attempting uninstall: rsa\n",
    "    Found existing installation: rsa 4.6\n",
    "    Uninstalling rsa-4.6:\n",
    "      Successfully uninstalled rsa-4.6\n",
    "  Attempting uninstall: pyasn1-modules\n",
    "    Found existing installation: pyasn1-modules 0.2.8\n",
    "    Uninstalling pyasn1-modules-0.2.8:\n",
    "      Successfully uninstalled pyasn1-modules-0.2.8\n",
    "  Attempting uninstall: cachetools\n",
    "    Found existing installation: cachetools 4.1.0\n",
    "    Uninstalling cachetools-4.1.0:\n",
    "      Successfully uninstalled cachetools-4.1.0\n",
    "  Attempting uninstall: setuptools\n",
    "    Found existing installation: setuptools 49.1.1\n",
    "    Uninstalling setuptools-49.1.1:\n",
    "      Successfully uninstalled setuptools-49.1.1\n",
    "  Attempting uninstall: google-auth\n",
    "    Found existing installation: google-auth 1.18.0\n",
    "    Uninstalling google-auth-1.18.0:\n",
    "      Successfully uninstalled google-auth-1.18.0\n",
    "  Attempting uninstall: oauthlib\n",
    "    Found existing installation: oauthlib 3.1.0\n",
    "    Uninstalling oauthlib-3.1.0:\n",
    "      Successfully uninstalled oauthlib-3.1.0\n",
    "  Attempting uninstall: chardet\n",
    "    Found existing installation: chardet 3.0.4\n",
    "    Uninstalling chardet-3.0.4:\n",
    "      Successfully uninstalled chardet-3.0.4\n",
    "  Attempting uninstall: certifi\n",
    "    Found existing installation: certifi 2019.9.11\n",
    "    Uninstalling certifi-2019.9.11:\n",
    "      Successfully uninstalled certifi-2019.9.11\n",
    "  Attempting uninstall: urllib3\n",
    "    Found existing installation: urllib3 1.24.2\n",
    "    Uninstalling urllib3-1.24.2:\n",
    "      Successfully uninstalled urllib3-1.24.2\n",
    "  Attempting uninstall: idna\n",
    "    Found existing installation: idna 2.8\n",
    "    Uninstalling idna-2.8:\n",
    "      Successfully uninstalled idna-2.8\n",
    "  Attempting uninstall: requests\n",
    "    Found existing installation: requests 2.22.0\n",
    "    Uninstalling requests-2.22.0:\n",
    "      Successfully uninstalled requests-2.22.0\n",
    "  Attempting uninstall: requests-oauthlib\n",
    "    Found existing installation: requests-oauthlib 1.3.0\n",
    "    Uninstalling requests-oauthlib-1.3.0:\n",
    "      Successfully uninstalled requests-oauthlib-1.3.0\n",
    "  Attempting uninstall: google-auth-oauthlib\n",
    "    Found existing installation: google-auth-oauthlib 0.4.1\n",
    "    Uninstalling google-auth-oauthlib-0.4.1:\n",
    "      Successfully uninstalled google-auth-oauthlib-0.4.1\n",
    "  Attempting uninstall: werkzeug\n",
    "    Found existing installation: Werkzeug 0.16.0\n",
    "    Uninstalling Werkzeug-0.16.0:\n",
    "      Successfully uninstalled Werkzeug-0.16.0\n",
    "  Attempting uninstall: absl-py\n",
    "    Found existing installation: absl-py 0.9.0\n",
    "    Uninstalling absl-py-0.9.0:\n",
    "      Successfully uninstalled absl-py-0.9.0\n",
    "  Attempting uninstall: tensorboard-plugin-wit\n",
    "    Found existing installation: tensorboard-plugin-wit 1.6.0.post3\n",
    "    Uninstalling tensorboard-plugin-wit-1.6.0.post3:\n",
    "      Successfully uninstalled tensorboard-plugin-wit-1.6.0.post3\n",
    "  Attempting uninstall: protobuf\n",
    "    Found existing installation: protobuf 3.12.2\n",
    "    Uninstalling protobuf-3.12.2:\n",
    "      Successfully uninstalled protobuf-3.12.2\n",
    "  Attempting uninstall: tensorboard\n",
    "    Found existing installation: tensorboard 2.2.2\n",
    "    Uninstalling tensorboard-2.2.2:\n",
    "      Successfully uninstalled tensorboard-2.2.2\n",
    "  Attempting uninstall: h5py\n",
    "    Found existing installation: h5py 2.10.0\n",
    "    Uninstalling h5py-2.10.0:\n",
    "      Successfully uninstalled h5py-2.10.0\n",
    "  Attempting uninstall: opt-einsum\n",
    "    Found existing installation: opt-einsum 3.2.1\n",
    "    Uninstalling opt-einsum-3.2.1:\n",
    "      Successfully uninstalled opt-einsum-3.2.1\n",
    "  Attempting uninstall: google-pasta\n",
    "    Found existing installation: google-pasta 0.2.0\n",
    "    Uninstalling google-pasta-0.2.0:\n",
    "      Successfully uninstalled google-pasta-0.2.0\n",
    "  Attempting uninstall: tensorflow-estimator\n",
    "    Found existing installation: tensorflow-estimator 2.2.0\n",
    "    Uninstalling tensorflow-estimator-2.2.0:\n",
    "      Successfully uninstalled tensorflow-estimator-2.2.0\n",
    "  Attempting uninstall: scipy\n",
    "    Found existing installation: scipy 1.4.1\n",
    "    Uninstalling scipy-1.4.1:\n",
    "      Successfully uninstalled scipy-1.4.1\n",
    "  Attempting uninstall: astunparse\n",
    "    Found existing installation: astunparse 1.6.3\n",
    "    Uninstalling astunparse-1.6.3:\n",
    "      Successfully uninstalled astunparse-1.6.3\n",
    "  Attempting uninstall: keras-preprocessing\n",
    "    Found existing installation: Keras-Preprocessing 1.1.2\n",
    "    Uninstalling Keras-Preprocessing-1.1.2:\n",
    "      Successfully uninstalled Keras-Preprocessing-1.1.2\n",
    "Successfully installed absl-py-0.9.0 astunparse-1.6.3 cachetools-4.1.1 certifi-2020.6.20 chardet-3.0.4 gast-0.3.3 google-auth-1.18.0 google-auth-oauthlib-0.4.1 google-pasta-0.2.0 grpcio-1.30.0 h5py-2.10.0 idna-2.10 importlib-metadata-1.7.0 keras-preprocessing-1.1.2 markdown-3.2.2 numpy-1.19.0 oauthlib-3.1.0 opt-einsum-3.2.1 protobuf-3.12.2 pyasn1-0.4.8 pyasn1-modules-0.2.8 requests-2.24.0 requests-oauthlib-1.3.0 rsa-4.6 scipy-1.4.1 setuptools-49.1.1 six-1.15.0 tensorboard-2.2.2 tensorboard-plugin-wit-1.7.0 tensorflow-estimator-2.2.0 tensorflow-gpu-2.2.0 termcolor-1.1.0 urllib3-1.25.9 werkzeug-1.0.1 wheel-0.34.2 wrapt-1.12.1 zipp-3.1.0\n",
    "Note: you may need to restart the kernel to use updated packages.\n",
    "\n",
    "import tensorflow as tf\n",
    "print(tf.version.VERSION)\n",
    "\n",
    "2.2.0\n",
    "\n",
    "pip install --user --upgrade tensorflow\n",
    "\n",
    "Collecting tensorflow\n",
    "  Using cached tensorflow-2.2.0-cp37-cp37m-manylinux2010_x86_64.whl (516.2 MB)\n",
    "Requirement already satisfied, skipping upgrade: absl-py>=0.7.0 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorflow) (0.9.0)\n",
    "Requirement already satisfied, skipping upgrade: numpy<2.0,>=1.16.0 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorflow) (1.19.0)\n",
    "Requirement already satisfied, skipping upgrade: protobuf>=3.8.0 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorflow) (3.12.2)\n",
    "Requirement already satisfied, skipping upgrade: wheel>=0.26; python_version >= \"3\" in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorflow) (0.34.2)\n",
    "Requirement already satisfied, skipping upgrade: h5py<2.11.0,>=2.10.0 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorflow) (2.10.0)\n",
    "Requirement already satisfied, skipping upgrade: termcolor>=1.1.0 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorflow) (1.1.0)\n",
    "Requirement already satisfied, skipping upgrade: six>=1.12.0 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorflow) (1.15.0)\n",
    "Requirement already satisfied, skipping upgrade: grpcio>=1.8.6 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorflow) (1.30.0)\n",
    "Requirement already satisfied, skipping upgrade: scipy==1.4.1; python_version >= \"3\" in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorflow) (1.4.1)\n",
    "Collecting tensorboard<2.3.0,>=2.2.0\n",
    "  Using cached tensorboard-2.2.2-py3-none-any.whl (3.0 MB)\n",
    "Requirement already satisfied, skipping upgrade: opt-einsum>=2.3.2 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorflow) (3.2.1)\n",
    "Requirement already satisfied, skipping upgrade: wrapt>=1.11.1 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorflow) (1.12.1)\n",
    "Requirement already satisfied, skipping upgrade: google-pasta>=0.1.8 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorflow) (0.2.0)\n",
    "Requirement already satisfied, skipping upgrade: astunparse==1.6.3 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorflow) (1.6.3)\n",
    "Requirement already satisfied, skipping upgrade: gast==0.3.3 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorflow) (0.3.3)\n",
    "Requirement already satisfied, skipping upgrade: keras-preprocessing>=1.1.0 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorflow) (1.1.2)\n",
    "Collecting tensorflow-estimator<2.3.0,>=2.2.0\n",
    "  Using cached tensorflow_estimator-2.2.0-py2.py3-none-any.whl (454 kB)\n",
    "Requirement already satisfied, skipping upgrade: setuptools in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from protobuf>=3.8.0->tensorflow) (49.1.1)\n",
    "Requirement already satisfied, skipping upgrade: requests<3,>=2.21.0 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow) (2.24.0)\n",
    "Requirement already satisfied, skipping upgrade: google-auth-oauthlib<0.5,>=0.4.1 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow) (0.4.1)\n",
    "Requirement already satisfied, skipping upgrade: google-auth<2,>=1.6.3 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow) (1.18.0)\n",
    "Requirement already satisfied, skipping upgrade: tensorboard-plugin-wit>=1.6.0 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow) (1.7.0)\n",
    "Requirement already satisfied, skipping upgrade: werkzeug>=0.11.15 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow) (1.0.1)\n",
    "Requirement already satisfied, skipping upgrade: markdown>=2.6.8 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow) (3.2.2)\n",
    "Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow) (2020.6.20)\n",
    "Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow) (1.25.9)\n",
    "Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow) (3.0.4)\n",
    "Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow) (2.10)\n",
    "Requirement already satisfied, skipping upgrade: requests-oauthlib>=0.7.0 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.3.0,>=2.2.0->tensorflow) (1.3.0)\n",
    "Requirement already satisfied, skipping upgrade: pyasn1-modules>=0.2.1 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow) (0.2.8)\n",
    "Requirement already satisfied, skipping upgrade: cachetools<5.0,>=2.0.0 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow) (4.1.1)\n",
    "Requirement already satisfied, skipping upgrade: rsa<5,>=3.1.4; python_version >= \"3\" in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow) (4.6)\n",
    "Requirement already satisfied, skipping upgrade: importlib-metadata; python_version < \"3.8\" in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from markdown>=2.6.8->tensorboard<2.3.0,>=2.2.0->tensorflow) (1.7.0)\n",
    "Requirement already satisfied, skipping upgrade: oauthlib>=3.0.0 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.3.0,>=2.2.0->tensorflow) (3.1.0)\n",
    "Requirement already satisfied, skipping upgrade: pyasn1<0.5.0,>=0.4.6 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow) (0.4.8)\n",
    "Requirement already satisfied, skipping upgrade: zipp>=0.5 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from importlib-metadata; python_version < \"3.8\"->markdown>=2.6.8->tensorboard<2.3.0,>=2.2.0->tensorflow) (3.1.0)\n",
    "Installing collected packages: tensorboard, tensorflow-estimator, tensorflow\n",
    "  WARNING: The script tensorboard is installed in '/home/ubuntu/.local/bin' which is not on PATH.\n",
    "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\n",
    "  WARNING: The scripts estimator_ckpt_converter, saved_model_cli, tensorboard, tf_upgrade_v2, tflite_convert, toco and toco_from_protos are installed in '/home/ubuntu/.local/bin' which is not on PATH.\n",
    "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\n",
    "Successfully installed tensorboard-2.2.2 tensorflow-2.2.0 tensorflow-estimator-2.2.0\n",
    "Note: you may need to restart the kernel to use updated packages.\n",
    "\n",
    " \n",
    "\n",
    "2.2.0\n",
    "\n",
    " \n",
    "\n",
    "from bert_serving.client import BertClient\n",
    "bc = BertClient(ip='129.128.208.15')\n",
    "print('client inited.')\n",
    "\n",
    "---------------------------------------------------------------------------\n",
    "KeyboardInterrupt                         Traceback (most recent call last)\n",
    "<ipython-input-1-9df503aa9fab> in <module>\n",
    "      1 from bert_serving.client import BertClient\n",
    "----> 2 bc = BertClient(ip='129.128.208.15')\n",
    "      3 print('client inited.')\n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/bert_serving/client/__init__.py in __init__(self, ip, port, port_out, output_fmt, show_server_config, identity, check_version, check_length, check_token_info, ignore_all_checks, timeout)\n",
    "    106 \n",
    "    107         if not ignore_all_checks and (check_version or show_server_config or check_length or check_token_info):\n",
    "--> 108             s_status = self.server_config\n",
    "    109 \n",
    "    110             if check_version and s_status['server_version'] != self.status['client_version']:\n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/bert_serving/client/__init__.py in arg_wrapper(self, *args, **kwargs)\n",
    "    204                 self.receiver.setsockopt(zmq.RCVTIMEO, self.timeout)\n",
    "    205             try:\n",
    "--> 206                 return func(self, *args, **kwargs)\n",
    "    207             except zmq.error.Again as _e:\n",
    "    208                 t_e = TimeoutError(\n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/bert_serving/client/__init__.py in server_config(self)\n",
    "    230         \"\"\"\n",
    "    231         req_id = self._send(b'SHOW_CONFIG')\n",
    "--> 232         return jsonapi.loads(self._recv(req_id).content[1])\n",
    "    233 \n",
    "    234     @property\n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/bert_serving/client/__init__.py in _recv(self, wait_for_req_id)\n",
    "    151 \n",
    "    152                 # receive a response\n",
    "--> 153                 response = self.receiver.recv_multipart()\n",
    "    154                 request_id = int(response[-1])\n",
    "    155 \n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/zmq/sugar/socket.py in recv_multipart(self, flags, copy, track)\n",
    "    473             for any of the reasons :func:`~Socket.recv` might fail\n",
    "    474         \"\"\"\n",
    "--> 475         parts = [self.recv(flags, copy=copy, track=track)]\n",
    "    476         # have first part already, only loop while more to receive\n",
    "    477         while self.getsockopt(zmq.RCVMORE):\n",
    "\n",
    "zmq/backend/cython/socket.pyx in zmq.backend.cython.socket.Socket.recv()\n",
    "\n",
    "zmq/backend/cython/socket.pyx in zmq.backend.cython.socket.Socket.recv()\n",
    "\n",
    "zmq/backend/cython/socket.pyx in zmq.backend.cython.socket._recv_copy()\n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/zmq/backend/cython/checkrc.pxd in zmq.backend.cython.checkrc._check_rc()\n",
    "\n",
    "KeyboardInterrupt: \n",
    "\n",
    "!wget https://tfhub.dev/tensorflow/albert_en_base/1 -O temp\n",
    "\n",
    "--2020-07-14 00:12:12--  https://tfhub.dev/tensorflow/albert_en_base/1\n",
    "Resolving tfhub.dev (tfhub.dev)... 172.217.3.174, 2607:f8b0:400a:804::200e\n",
    "Connecting to tfhub.dev (tfhub.dev)|172.217.3.174|:443... connected.\n",
    "HTTP request sent, awaiting response... 200 OK\n",
    "Length: unspecified [text/html]\n",
    "Saving to: ‘temp’\n",
    "\n",
    "temp                    [ <=>                ]   1.20K  --.-KB/s    in 0s      \n",
    "\n",
    "2020-07-14 00:12:12 (18.1 MB/s) - ‘temp’ saved [1229]\n",
    "\n",
    "ls\n",
    "\n",
    "1    1.tar       NLP_4_1.ipynb  Sae-NLP1.ipynb  temp             Untitled.ipynb\n",
    "1.1  bert_repo/  Sae/           Sae-P2.ipynb    Untitled1.ipynb\n",
    "\n",
    "max_seq_length = 128\n",
    "\n",
    "input_word_ids = tf.keras.layers.Input(shape=(max_seq_length,), dtype=tf.int32, name=\"input_word_ids\")\n",
    "\n",
    "input_mask = tf.keras.layers.Input(shape=(max_seq_length,), dtype=tf.int32, name=\"input_mask\")\n",
    "\n",
    "segment_ids = tf.keras.layers.Input(shape=(max_seq_length,), dtype=tf.int32, name=\"segment_ids\")\n",
    "\n",
    "import tensorflow_hub as hub\n",
    "\n",
    "albert_layer = hub.KerasLayer(\"https://tfhub.dev/tensorflow/albert_en_base/1\", trainable=True)\n",
    "\n",
    "pooled_output, sequence_output = albert_layer([input_word_ids, input_mask, segment_ids])\n",
    "\n",
    "pooled_output\n",
    "\n",
    "<tf.Tensor 'keras_layer/Identity:0' shape=(None, 768) dtype=float32>\n",
    "\n",
    "sequence_output\n",
    "\n",
    "<tf.Tensor 'keras_layer/Identity_1:0' shape=(None, None, 768) dtype=float32>\n",
    "\n",
    "sp_model_file = albert_layer.resolved_object.sp_model_file.asset_path.numpy()\n",
    "\n",
    "tokenizer = tokenization.FullSentencePieceTokenizer(sp_model_file)\n",
    "\n",
    "---------------------------------------------------------------------------\n",
    "NameError                                 Traceback (most recent call last)\n",
    "<ipython-input-33-0782b4971b42> in <module>\n",
    "----> 1 tokenizer = tokenization.FullSentencePieceTokenizer(sp_model_file)\n",
    "\n",
    "NameError: name 'tokenization' is not defined\n",
    "\n",
    "import sys\n",
    "import time\n",
    "\n",
    "from random import choice\n",
    "import string\n",
    "\n",
    "import numpy as np\n",
    "\n",
    "from service.client import BertClient\n",
    "\n",
    "def GenRandomText(length=8, chars=string.ascii_letters + string.digits):\n",
    "    return ''.join([choice(chars) for i in range(length)])\n",
    "\n",
    "def cosine_sim(a, b):\n",
    "    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    from service.client import BertClient\n",
    "    bc = BertClient(ip='localhost', port=5555)\n",
    "\n",
    "    for i in range(1, 10):\n",
    "        \n",
    "        leftTerm = GenRandomText(3,string.ascii_letters)\n",
    "        rightTerm = \"how are you today?\"\n",
    "\n",
    "        leftV = bc.encode([leftTerm])\n",
    "        rightV = bc.encode([rightTerm ])\n",
    "\n",
    "        cosine_similarity = cosine_sim(leftV[0],rightV[0])\n",
    "        \n",
    "        print(\"left: %s right: %s distance: %f\" % (leftTerm,rightTerm,cosine_similarity) )\n",
    "\n",
    "---------------------------------------------------------------------------\n",
    "ModuleNotFoundError                       Traceback (most recent call last)\n",
    "<ipython-input-5-3e1082fe35db> in <module>\n",
    "      7 import numpy as np\n",
    "      8 \n",
    "----> 9 from service.client import BertClient\n",
    "     10 \n",
    "     11 def GenRandomText(length=8, chars=string.ascii_letters + string.digits):\n",
    "\n",
    "ModuleNotFoundError: No module named 'service'\n",
    "\n",
    "from bert_serving.client import BertClient\n",
    "\n",
    "ec = BertClient()\n",
    "print(\"sss\")\n",
    "\n",
    "---------------------------------------------------------------------------\n",
    "KeyboardInterrupt                         Traceback (most recent call last)\n",
    "<ipython-input-25-4aedc267d559> in <module>\n",
    "----> 1 ec = BertClient()\n",
    "      2 print(\"sss\")\n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/bert_serving/client/__init__.py in __init__(self, ip, port, port_out, output_fmt, show_server_config, identity, check_version, check_length, check_token_info, ignore_all_checks, timeout)\n",
    "    106 \n",
    "    107         if not ignore_all_checks and (check_version or show_server_config or check_length or check_token_info):\n",
    "--> 108             s_status = self.server_config\n",
    "    109 \n",
    "    110             if check_version and s_status['server_version'] != self.status['client_version']:\n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/bert_serving/client/__init__.py in arg_wrapper(self, *args, **kwargs)\n",
    "    204                 self.receiver.setsockopt(zmq.RCVTIMEO, self.timeout)\n",
    "    205             try:\n",
    "--> 206                 return func(self, *args, **kwargs)\n",
    "    207             except zmq.error.Again as _e:\n",
    "    208                 t_e = TimeoutError(\n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/bert_serving/client/__init__.py in server_config(self)\n",
    "    230         \"\"\"\n",
    "    231         req_id = self._send(b'SHOW_CONFIG')\n",
    "--> 232         return jsonapi.loads(self._recv(req_id).content[1])\n",
    "    233 \n",
    "    234     @property\n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/bert_serving/client/__init__.py in _recv(self, wait_for_req_id)\n",
    "    151 \n",
    "    152                 # receive a response\n",
    "--> 153                 response = self.receiver.recv_multipart()\n",
    "    154                 request_id = int(response[-1])\n",
    "    155 \n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/zmq/sugar/socket.py in recv_multipart(self, flags, copy, track)\n",
    "    473             for any of the reasons :func:`~Socket.recv` might fail\n",
    "    474         \"\"\"\n",
    "--> 475         parts = [self.recv(flags, copy=copy, track=track)]\n",
    "    476         # have first part already, only loop while more to receive\n",
    "    477         while self.getsockopt(zmq.RCVMORE):\n",
    "\n",
    "zmq/backend/cython/socket.pyx in zmq.backend.cython.socket.Socket.recv()\n",
    "\n",
    "zmq/backend/cython/socket.pyx in zmq.backend.cython.socket.Socket.recv()\n",
    "\n",
    "zmq/backend/cython/socket.pyx in zmq.backend.cython.socket._recv_copy()\n",
    "\n",
    "~/anaconda3/lib/python3.7/site-packages/zmq/backend/cython/checkrc.pxd in zmq.backend.cython.checkrc._check_rc()\n",
    "\n",
    "KeyboardInterrupt: \n",
    "\n",
    "import uuid\n",
    "\n",
    "import numpy as np\n",
    "import zmq\n",
    "from zmq.utils import jsonapi\n",
    "\n",
    "\n",
    "class BertClient:\n",
    "    def __init__(self, ip='localhost', port=8888, output_fmt='ndarray', show_server_config=True):\n",
    "        self.socket = zmq.Context().socket(zmq.REQ)\n",
    "        self.socket.identity = str(uuid.uuid4()).encode('ascii')\n",
    "        self.socket.connect('tcp://%s:%d' % (ip, port))\n",
    "        self.ip = ip\n",
    "        self.port = port\n",
    "\n",
    "        if output_fmt == 'ndarray':\n",
    "            self.formatter = lambda x: x\n",
    "        elif output_fmt == 'list':\n",
    "            self.formatter = lambda x: x.tolist()\n",
    "        else:\n",
    "            raise AttributeError('\"output_fmt\" must be \"ndarray\" or \"list\"')\n",
    "\n",
    "        if show_server_config:\n",
    "            self.get_server_config()\n",
    "            print('you should NOT see this message multiple times! '\n",
    "                  'if you see it appears repeatedly, '\n",
    "                  'please consider moving \"BertClient()\" out of the loop.')\n",
    "\n",
    "    def get_server_config(self):\n",
    "        self.socket.send(b'SHOW_CONFIG')\n",
    "        response = self.socket.recv_multipart()\n",
    "        print('the server at %s:%d returns the following config:' % (self.ip, self.port))\n",
    "        for k, v in jsonapi.loads(response[0]).items():\n",
    "            print('%30s\\t=\\t%-30s' % (k, v))\n",
    "\n",
    "    def encode(self, texts):\n",
    "        if self.is_valid_input(texts):\n",
    "            self.socket.send_pyobj(texts)\n",
    "            response = self.socket.recv_multipart()\n",
    "            arr_info, arr_val = jsonapi.loads(response[0]), response[3]\n",
    "            X = np.frombuffer(memoryview(arr_val), dtype=arr_info['dtype'])\n",
    "            return self.formatter(X.reshape(arr_info['shape']))\n",
    "        else:\n",
    "            raise AttributeError('\"texts\" must be \"List[str]\" and non-empty!')\n",
    "\n",
    "    @staticmethod\n",
    "    def is_valid_input(texts):\n",
    "        return isinstance(texts, list) and all(isinstance(s, str) and s.strip() for s in texts)\n",
    "\n",
    "!wget https://github.com/jageshmaharjan/BERT_Service/archive/master.zip -O tmp2.zip\n",
    "\n",
    "--2020-07-14 06:03:51--  https://github.com/jageshmaharjan/BERT_Service/archive/master.zip\n",
    "Resolving github.com (github.com)... 140.82.114.3\n",
    "Connecting to github.com (github.com)|140.82.114.3|:443... connected.\n",
    "HTTP request sent, awaiting response... 302 Found\n",
    "Location: https://codeload.github.com/jageshmaharjan/BERT_Service/zip/master [following]\n",
    "--2020-07-14 06:03:51--  https://codeload.github.com/jageshmaharjan/BERT_Service/zip/master\n",
    "Resolving codeload.github.com (codeload.github.com)... 140.82.112.9\n",
    "Connecting to codeload.github.com (codeload.github.com)|140.82.112.9|:443... connected.\n",
    "HTTP request sent, awaiting response... 200 OK\n",
    "Length: unspecified [application/zip]\n",
    "Saving to: ‘tmp2.zip’\n",
    "\n",
    "tmp2.zip                [  <=>               ] 234.69K  1.02MB/s    in 0.2s    \n",
    "\n",
    "2020-07-14 06:03:52 (1.02 MB/s) - ‘tmp2.zip’ saved [240320]\n",
    "\n",
    "!unzip tmp2.zip\n",
    "\n",
    "Archive:  tmp2.zip\n",
    "06f0059e1ab8781d524f4698b2e8a742cacbd796\n",
    "   creating: BERT_Service-master/\n",
    "   creating: BERT_Service-master/.github/\n",
    "   creating: BERT_Service-master/.github/workflows/\n",
    "  inflating: BERT_Service-master/.github/workflows/blank.yml  \n",
    "  inflating: BERT_Service-master/=   \n",
    "  inflating: BERT_Service-master/BERT_sentence_similarity.ipynb  \n",
    "  inflating: BERT_Service-master/LICENSE  \n",
    "  inflating: BERT_Service-master/README.md  \n",
    "  inflating: BERT_Service-master/Word2Vec.ipynb  \n",
    "  inflating: BERT_Service-master/__init__.py  \n",
    "  inflating: BERT_Service-master/app.py  \n",
    "  inflating: BERT_Service-master/azure-pipelines.yml  \n",
    "  inflating: BERT_Service-master/benchmark.py  \n",
    "   creating: BERT_Service-master/bert/\n",
    "  inflating: BERT_Service-master/bert/__init__.py  \n",
    "  inflating: BERT_Service-master/bert/extract_features.py  \n",
    "  inflating: BERT_Service-master/bert/modeling.py  \n",
    "  inflating: BERT_Service-master/bert/modeling_test.py  \n",
    "  inflating: BERT_Service-master/bert/optimization.py  \n",
    "  inflating: BERT_Service-master/bert/optimization_test.py  \n",
    "  inflating: BERT_Service-master/bert/tokenization.py  \n",
    "  inflating: BERT_Service-master/bert/tokenization_test.py  \n",
    "  inflating: BERT_Service-master/client_example.py  \n",
    "   creating: BERT_Service-master/docker/\n",
    "  inflating: BERT_Service-master/docker/Dockerfile  \n",
    "  inflating: BERT_Service-master/docker/entrypoint.sh  \n",
    "  inflating: BERT_Service-master/gpu_env.py  \n",
    "  inflating: BERT_Service-master/helper.py  \n",
    "   creating: BERT_Service-master/manifests/\n",
    "  inflating: BERT_Service-master/manifests/deployment.yml  \n",
    "  inflating: BERT_Service-master/manifests/service.yml  \n",
    "  inflating: BERT_Service-master/requirements.client.txt  \n",
    "  inflating: BERT_Service-master/requirements.gpu.txt  \n",
    "  inflating: BERT_Service-master/requirements.txt  \n",
    "   creating: BERT_Service-master/service/\n",
    " extracting: BERT_Service-master/service/__init__.py  \n",
    "  inflating: BERT_Service-master/service/client.py  \n",
    "  inflating: BERT_Service-master/service/server.py  \n",
    "\n",
    "ls\n",
    "\n",
    "1      bert_repo/            Sae/            temp             Untitled.ipynb\n",
    "1.1    BERT_Service-master/  Sae-NLP1.ipynb  tmp2.zip\n",
    "1.tar  NLP_4_1.ipynb         Sae-P2.ipynb    Untitled1.ipynb\n",
    "\n",
    "!bert-serving-start -num_worker=4 -model_dir /uncased_L-24_H-1024_A-16/\n",
    "\n",
    "/home/ubuntu/anaconda3/lib/python3.7/site-packages/bert_serving/server/helper.py:176: UserWarning: Tensorflow 2.2.0 is not tested! It may or may not work. Feel free to submit an issue at https://github.com/hanxiao/bert-as-service/issues/\n",
    "  'Feel free to submit an issue at https://github.com/hanxiao/bert-as-service/issues/' % tf.__version__)\n",
    "usage: /home/ubuntu/anaconda3/bin/bert-serving-start -num_worker=4 -model_dir /uncased_L-24_H-1024_A-16/\n",
    "                 ARG   VALUE\n",
    "__________________________________________________\n",
    "           ckpt_name = bert_model.ckpt\n",
    "         config_name = bert_config.json\n",
    "                cors = *\n",
    "                 cpu = False\n",
    "          device_map = []\n",
    "       do_lower_case = True\n",
    "  fixed_embed_length = False\n",
    "                fp16 = False\n",
    " gpu_memory_fraction = 0.5\n",
    "       graph_tmp_dir = None\n",
    "    http_max_connect = 10\n",
    "           http_port = None\n",
    "        mask_cls_sep = False\n",
    "      max_batch_size = 256\n",
    "         max_seq_len = 25\n",
    "           model_dir = /uncased_L-24_H-1024_A-16/\n",
    "no_position_embeddings = False\n",
    "    no_special_token = False\n",
    "          num_worker = 4\n",
    "       pooling_layer = [-2]\n",
    "    pooling_strategy = REDUCE_MEAN\n",
    "                port = 5555\n",
    "            port_out = 5556\n",
    "       prefetch_size = 10\n",
    " priority_batch_size = 16\n",
    "show_tokens_to_client = False\n",
    "     tuned_model_dir = None\n",
    "             verbose = False\n",
    "                 xla = False\n",
    "\n",
    "I:VENTILATOR:[__i:__i: 67]:freeze, optimize and export graph, could take a while...\n",
    "I:GRAPHOPT:[gra:opt: 53]:model config: /uncased_L-24_H-1024_A-16/bert_config.json\n",
    "I:GRAPHOPT:[gra:opt: 56]:checkpoint: /uncased_L-24_H-1024_A-16/bert_model.ckpt\n",
    "E:GRAPHOPT:[gra:opt:154]:fail to optimize the graph!\n",
    "Traceback (most recent call last):\n",
    "  File \"/home/ubuntu/anaconda3/lib/python3.7/site-packages/bert_serving/server/graph.py\", line 58, in optimize_graph\n",
    "    bert_config = modeling.BertConfig.from_dict(json.load(f))\n",
    "  File \"/home/ubuntu/anaconda3/lib/python3.7/json/__init__.py\", line 293, in load\n",
    "    return loads(fp.read(),\n",
    "  File \"/home/ubuntu/.local/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 116, in read\n",
    "    self._preread_check()\n",
    "  File \"/home/ubuntu/.local/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py\", line 79, in _preread_check\n",
    "    self.__name, 1024 * 512)\n",
    "tensorflow.python.framework.errors_impl.NotFoundError: /uncased_L-24_H-1024_A-16/bert_config.json; No such file or directory\n",
    "Traceback (most recent call last):\n",
    "  File \"/home/ubuntu/anaconda3/bin/bert-serving-start\", line 10, in <module>\n",
    "    sys.exit(main())\n",
    "  File \"/home/ubuntu/anaconda3/lib/python3.7/site-packages/bert_serving/server/cli/__init__.py\", line 4, in main\n",
    "    with BertServer(get_run_args()) as server:\n",
    "  File \"/home/ubuntu/anaconda3/lib/python3.7/site-packages/bert_serving/server/__init__.py\", line 71, in __init__\n",
    "    self.graph_path, self.bert_config = pool.apply(optimize_graph, (self.args,))\n",
    "TypeError: cannot unpack non-iterable NoneType object\n",
    "\n",
    "!bert-serving-start -model_dir /home/ubuntu/anaconda3/lib/python3.7/site-packages/uncased_L-24_H-1024_A-16/\n",
    "\n",
    "/home/ubuntu/anaconda3/lib/python3.7/site-packages/bert_serving/server/helper.py:176: UserWarning: Tensorflow 2.2.0 is not tested! It may or may not work. Feel free to submit an issue at https://github.com/hanxiao/bert-as-service/issues/\n",
    "  'Feel free to submit an issue at https://github.com/hanxiao/bert-as-service/issues/' % tf.__version__)\n",
    "usage: /home/ubuntu/anaconda3/bin/bert-serving-start -model_dir /home/ubuntu/anaconda3/lib/python3.7/site-packages/uncased_L-24_H-1024_A-16/\n",
    "                 ARG   VALUE\n",
    "__________________________________________________\n",
    "           ckpt_name = bert_model.ckpt\n",
    "         config_name = bert_config.json\n",
    "                cors = *\n",
    "                 cpu = False\n",
    "          device_map = []\n",
    "       do_lower_case = True\n",
    "  fixed_embed_length = False\n",
    "                fp16 = False\n",
    " gpu_memory_fraction = 0.5\n",
    "       graph_tmp_dir = None\n",
    "    http_max_connect = 10\n",
    "           http_port = None\n",
    "        mask_cls_sep = False\n",
    "      max_batch_size = 256\n",
    "         max_seq_len = 25\n",
    "           model_dir = /home/ubuntu/anaconda3/lib/python3.7/site-packages/uncased_L-24_H-1024_A-16/\n",
    "no_position_embeddings = False\n",
    "    no_special_token = False\n",
    "          num_worker = 1\n",
    "       pooling_layer = [-2]\n",
    "    pooling_strategy = REDUCE_MEAN\n",
    "                port = 5555\n",
    "            port_out = 5556\n",
    "       prefetch_size = 10\n",
    " priority_batch_size = 16\n",
    "show_tokens_to_client = False\n",
    "     tuned_model_dir = None\n",
    "             verbose = False\n",
    "                 xla = False\n",
    "\n",
    "I:VENTILATOR:[__i:__i: 67]:freeze, optimize and export graph, could take a while...\n",
    "I:GRAPHOPT:[gra:opt: 53]:model config: /home/ubuntu/anaconda3/lib/python3.7/site-packages/uncased_L-24_H-1024_A-16/bert_config.json\n",
    "I:GRAPHOPT:[gra:opt: 56]:checkpoint: /home/ubuntu/anaconda3/lib/python3.7/site-packages/uncased_L-24_H-1024_A-16/bert_model.ckpt\n",
    "I:GRAPHOPT:[gra:opt: 60]:build graph...\n",
    "E:GRAPHOPT:[gra:opt:154]:fail to optimize the graph!\n",
    "Traceback (most recent call last):\n",
    "  File \"/home/ubuntu/anaconda3/lib/python3.7/site-packages/bert_serving/server/graph.py\", line 62, in optimize_graph\n",
    "    input_ids = tf.compat.v1.placeholder(tf.int32, (None, None), 'input_ids')\n",
    "  File \"/home/ubuntu/.local/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py\", line 3023, in placeholder\n",
    "    raise RuntimeError(\"tf.compat.v1.placeholder() is not compatible with \"\n",
    "RuntimeError: tf.compat.v1.placeholder() is not compatible with eager execution.\n",
    "Traceback (most recent call last):\n",
    "  File \"/home/ubuntu/anaconda3/bin/bert-serving-start\", line 10, in <module>\n",
    "    sys.exit(main())\n",
    "  File \"/home/ubuntu/anaconda3/lib/python3.7/site-packages/bert_serving/server/cli/__init__.py\", line 4, in main\n",
    "    with BertServer(get_run_args()) as server:\n",
    "  File \"/home/ubuntu/anaconda3/lib/python3.7/site-packages/bert_serving/server/__init__.py\", line 71, in __init__\n",
    "    self.graph_path, self.bert_config = pool.apply(optimize_graph, (self.args,))\n",
    "TypeError: cannot unpack non-iterable NoneType object\n",
    "\n",
    "!sed -i 's/tf.placeholder/tf.compat.v1.placeholder/g' /home/ubuntu/.local/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py\n",
    "\n",
    "ll\n",
    "\n",
    "total 1315476\n",
    "-rw-r--r-- 1 ubuntu        314 Oct 18  2018 bert_config.json\n",
    "-rw-r--r-- 1 ubuntu 1344904432 Oct 18  2018 bert_model.ckpt.data-00000-of-00001\n",
    "-rw-r--r-- 1 ubuntu      16530 Oct 18  2018 bert_model.ckpt.index\n",
    "-rw-r--r-- 1 ubuntu    1878861 Oct 18  2018 bert_model.ckpt.meta\n",
    "-rw-r--r-- 1 ubuntu     231508 Oct 18  2018 vocab.txt\n",
    "\n",
    "pwd\n",
    "\n",
    "'/home/ubuntu/anaconda3/lib/python3.7/site-packages/uncased_L-24_H-1024_A-16'\n",
    "\n",
    "pip install tensorflow==1.13.1\n",
    "\n",
    "Collecting tensorflow==1.13.1\n",
    "  Using cached tensorflow-1.13.1-cp37-cp37m-manylinux1_x86_64.whl (92.6 MB)\n",
    "Requirement already satisfied: astor>=0.6.0 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorflow==1.13.1) (0.8.1)\n",
    "Requirement already satisfied: numpy>=1.13.3 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorflow==1.13.1) (1.19.0)\n",
    "Requirement already satisfied: keras-preprocessing>=1.0.5 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorflow==1.13.1) (1.1.2)\n",
    "Requirement already satisfied: six>=1.10.0 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorflow==1.13.1) (1.15.0)\n",
    "Requirement already satisfied: absl-py>=0.1.6 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorflow==1.13.1) (0.9.0)\n",
    "Requirement already satisfied: termcolor>=1.1.0 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorflow==1.13.1) (1.1.0)\n",
    "Requirement already satisfied: grpcio>=1.8.6 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorflow==1.13.1) (1.30.0)\n",
    "Requirement already satisfied: wheel>=0.26 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorflow==1.13.1) (0.34.2)\n",
    "Requirement already satisfied: protobuf>=3.6.1 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorflow==1.13.1) (3.12.2)\n",
    "Collecting tensorboard<1.14.0,>=1.13.0\n",
    "  Using cached tensorboard-1.13.1-py3-none-any.whl (3.2 MB)\n",
    "Collecting tensorflow-estimator<1.14.0rc0,>=1.13.0\n",
    "  Using cached tensorflow_estimator-1.13.0-py2.py3-none-any.whl (367 kB)\n",
    "Requirement already satisfied: gast>=0.2.0 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorflow==1.13.1) (0.3.3)\n",
    "Requirement already satisfied: keras-applications>=1.0.6 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorflow==1.13.1) (1.0.8)\n",
    "Requirement already satisfied: setuptools in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from protobuf>=3.6.1->tensorflow==1.13.1) (49.1.1)\n",
    "Requirement already satisfied: werkzeug>=0.11.15 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorboard<1.14.0,>=1.13.0->tensorflow==1.13.1) (1.0.1)\n",
    "Requirement already satisfied: markdown>=2.6.8 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorboard<1.14.0,>=1.13.0->tensorflow==1.13.1) (3.2.2)\n",
    "Requirement already satisfied: mock>=2.0.0 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from tensorflow-estimator<1.14.0rc0,>=1.13.0->tensorflow==1.13.1) (3.0.5)\n",
    "Requirement already satisfied: h5py in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from keras-applications>=1.0.6->tensorflow==1.13.1) (2.10.0)\n",
    "Requirement already satisfied: importlib-metadata; python_version < \"3.8\" in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from markdown>=2.6.8->tensorboard<1.14.0,>=1.13.0->tensorflow==1.13.1) (1.7.0)\n",
    "Requirement already satisfied: zipp>=0.5 in /home/ubuntu/anaconda3/lib/python3.7/site-packages (from importlib-metadata; python_version < \"3.8\"->markdown>=2.6.8->tensorboard<1.14.0,>=1.13.0->tensorflow==1.13.1) (3.1.0)\n",
    "ERROR: tensorflow-gpu 2.2.0 has requirement tensorboard<2.3.0,>=2.2.0, but you'll have tensorboard 1.13.1 which is incompatible.\n",
    "ERROR: tensorflow-gpu 2.2.0 has requirement tensorflow-estimator<2.3.0,>=2.2.0, but you'll have tensorflow-estimator 1.13.0 which is incompatible.\n",
    "Installing collected packages: tensorboard, tensorflow-estimator, tensorflow\n",
    "  Attempting uninstall: tensorboard\n",
    "    Found existing installation: tensorboard 2.2.2\n",
    "    Uninstalling tensorboard-2.2.2:\n",
    "      Successfully uninstalled tensorboard-2.2.2\n",
    "  Attempting uninstall: tensorflow-estimator\n",
    "    Found existing installation: tensorflow-estimator 2.2.0\n",
    "    Uninstalling tensorflow-estimator-2.2.0:\n",
    "      Successfully uninstalled tensorflow-estimator-2.2.0\n",
    "  Attempting uninstall: tensorflow\n",
    "    Found existing installation: tensorflow 2.2.0\n",
    "    Uninstalling tensorflow-2.2.0:\n",
    "      Successfully uninstalled tensorflow-2.2.0\n",
    "Successfully installed tensorboard-1.13.1 tensorflow-1.13.1 tensorflow-estimator-1.14.0rc0\n",
    "Note: you may need to restart the kernel to use updated packages.\n",
    "\n",
    "import tensorflow as tf\n",
    "\n",
    "pip install tensorflow-estimator==1.14.0rc\n",
    "\n",
    "Collecting tensorflow-estimator==1.14.0rc0\n",
    "  Downloading tensorflow_estimator-1.14.0rc0-py2.py3-none-any.whl (487 kB)\n",
    "     |████████████████████████████████| 487 kB 1.8 MB/s eta 0:00:01\n",
    "ERROR: tensorflow 1.13.1 has requirement tensorflow-estimator<1.14.0rc0,>=1.13.0, but you'll have tensorflow-estimator 1.14.0rc0 which is incompatible.\n",
    "ERROR: tensorflow-gpu 2.2.0 has requirement tensorboard<2.3.0,>=2.2.0, but you'll have tensorboard 1.13.1 which is incompatible.\n",
    "ERROR: tensorflow-gpu 2.2.0 has requirement tensorflow-estimator<2.3.0,>=2.2.0, but you'll have tensorflow-estimator 1.14.0rc0 which is incompatible.\n",
    "Installing collected packages: tensorflow-estimator\n",
    "  Attempting uninstall: tensorflow-estimator\n",
    "    Found existing installation: tensorflow-estimator 1.13.0rc0\n",
    "    Uninstalling tensorflow-estimator-1.13.0rc0:\n",
    "      Successfully uninstalled tensorflow-estimator-1.13.0rc0\n",
    "Successfully installed tensorflow-estimator-1.14.0rc0\n",
    "Note: you may need to restart the kernel to use updated packages.\n",
    "\n",
    "!tf_upgrade_v2 --infile /home/ubuntu/anaconda3/lib/python3.7/site-packages/bert_serving/server/graph.py --outfile /home/ubuntu/.local/lib/python3.7/site-packages/tensorflow/tools/compatibility/tf_upgrade_v2_main.py\n",
    "\n",
    "Traceback (most recent call last):\n",
    "  File \"/home/ubuntu/.local/bin/tf_upgrade_v2\", line 5, in <module>\n",
    "    from tensorflow.tools.compatibility.tf_upgrade_v2_main import main\n",
    "  File \"/home/ubuntu/.local/lib/python3.7/site-packages/tensorflow/tools/compatibility/tf_upgrade_v2_main.py\", line 9, in <module>\n",
    "    from .bert import modeling\n",
    "ModuleNotFoundError: No module named 'tensorflow.tools.compatibility.bert'\n",
    "\n",
    " \n",
    "\n",
    "ls\n",
    "\n",
    "all_renames_v2.py  module_deprecations_v2.py  tf_upgrade_v2_main.py\n",
    "ast_edits.py       __pycache__/               tf_upgrade_v2.py\n",
    "__init__.py        renames_v2.py              tf_upgrade_v2_safety.py\n",
    "ipynb.py           reorders_v2.py\n",
    "\n",
    "SEQ_LEN = 128\n",
    "BATCH_SIZE = 128\n",
    "EPOCHS = 5\n",
    "LR = 1e-4\n",
    "\n",
    "import os\n",
    "\n",
    "pretrained_path = 'uncased_L-12_H-768_A-12'\n",
    "config_path = os.path.join(pretrained_path, 'bert_config.json')\n",
    "checkpoint_path = os.path.join(pretrained_path, 'bert_model.ckpt')\n",
    "vocab_path = os.path.join(pretrained_path, 'vocab.txt')\n",
    "\n",
    "# TF_KERAS must be added to environment variables in order to use TPU\n",
    "os.environ['TF_KERAS'] = '1'\n",
    "\n",
    "import tensorflow as tf\n",
    "from keras_bert import get_custom_objects\n",
    "\n",
    "TPU_WORKER = 'grpc://' + os.environ['COLAB_TPU_ADDR']\n",
    "resolver = tf.contrib.cluster_resolver.TPUClusterResolver(TPU_WORKER)\n",
    "tf.contrib.distribute.initialize_tpu_system(resolver)\n",
    "strategy = tf.contrib.distribute.TPUStrategy(resolver)\n",
    "\n",
    "---------------------------------------------------------------------------\n",
    "NameError                                 Traceback (most recent call last)\n",
    "<ipython-input-1-5f27d03ebbff> in <module>\n",
    "      2 from keras_bert import get_custom_objects\n",
    "      3 \n",
    "----> 4 TPU_WORKER = 'grpc://' + os.environ['COLAB_TPU_ADDR']\n",
    "      5 resolver = tf.contrib.cluster_resolver.TPUClusterResolver(TPU_WORKER)\n",
    "      6 tf.contrib.distribute.initialize_tpu_system(resolver)\n",
    "\n",
    "NameError: name 'os' is not defined\n",
    "\n",
    "import tensorflow as tf\n",
    "print(tf.__version__)\n",
    "\n",
    "2.2.0\n",
    "\n",
    "import codecs\n",
    "from keras_bert import load_trained_model_from_checkpoint\n",
    "\n",
    "token_dict = {}\n",
    "with codecs.open(vocab_path, 'r', 'utf8') as reader:\n",
    "    for line in reader:\n",
    "        token = line.strip()\n",
    "        token_dict[token] = len(token_dict)\n",
    "\n",
    "with strategy.scope():\n",
    "    model = load_trained_model_from_checkpoint(\n",
    "        config_path,\n",
    "        checkpoint_path,\n",
    "        training=True,\n",
    "        trainable=True,\n",
    "        seq_len=SEQ_LEN,\n",
    "    )\n",
    "\n",
    "---------------------------------------------------------------------------\n",
    "NameError                                 Traceback (most recent call last)\n",
    "<ipython-input-4-c8e0e56643e4> in <module>\n",
    "      3 \n",
    "      4 token_dict = {}\n",
    "----> 5 with codecs.open(vocab_path, 'r', 'utf8') as reader:\n",
    "      6     for line in reader:\n",
    "      7         token = line.strip()\n",
    "\n",
    "NameError: name 'vocab_path' is not defined\n",
    "\n",
    " \n",
    "\n",
    "!pip install tensorflow_estimator\n",
    "\n",
    "Collecting tensorflow_estimator\n",
    "  Using cached tensorflow_estimator-2.2.0-py2.py3-none-any.whl (454 kB)\n",
    "Installing collected packages: tensorflow-estimator\n",
    "Successfully installed tensorflow-estimator-2.2.0\n",
    "\n",
    " \n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
